/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuditEvent } from './AuditEvent';
import {
    AuditEventFromJSON,
    AuditEventFromJSONTyped,
    AuditEventToJSON,
    AuditEventToJSONTyped,
} from './AuditEvent';

/**
 * 
 * @export
 * @interface AuditEventsResponse
 */
export interface AuditEventsResponse {
    /**
     * 
     * @type {Array<AuditEvent>}
     * @memberof AuditEventsResponse
     */
    items?: Array<AuditEvent>;
    /**
     * 
     * @type {number}
     * @memberof AuditEventsResponse
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof AuditEventsResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof AuditEventsResponse
     */
    offset?: number;
}

/**
 * Check if a given object implements the AuditEventsResponse interface.
 */
export function instanceOfAuditEventsResponse(value: object): value is AuditEventsResponse {
    return true;
}

export function AuditEventsResponseFromJSON(json: any): AuditEventsResponse {
    return AuditEventsResponseFromJSONTyped(json, false);
}

export function AuditEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(AuditEventFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function AuditEventsResponseToJSON(json: any): AuditEventsResponse {
    return AuditEventsResponseToJSONTyped(json, false);
}

export function AuditEventsResponseToJSONTyped(value?: AuditEventsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(AuditEventToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

