/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommissionRow } from './CommissionRow';
import {
    CommissionRowFromJSON,
    CommissionRowFromJSONTyped,
    CommissionRowToJSON,
    CommissionRowToJSONTyped,
} from './CommissionRow';

/**
 * 
 * @export
 * @interface CommissionsResponse
 */
export interface CommissionsResponse {
    /**
     * 
     * @type {Array<CommissionRow>}
     * @memberof CommissionsResponse
     */
    items?: Array<CommissionRow>;
    /**
     * 
     * @type {number}
     * @memberof CommissionsResponse
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof CommissionsResponse
     */
    totalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CommissionsResponse
     */
    totalCommission?: number;
}

/**
 * Check if a given object implements the CommissionsResponse interface.
 */
export function instanceOfCommissionsResponse(value: object): value is CommissionsResponse {
    return true;
}

export function CommissionsResponseFromJSON(json: any): CommissionsResponse {
    return CommissionsResponseFromJSONTyped(json, false);
}

export function CommissionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommissionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CommissionRowFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'totalCommission': json['totalCommission'] == null ? undefined : json['totalCommission'],
    };
}

export function CommissionsResponseToJSON(json: any): CommissionsResponse {
    return CommissionsResponseToJSONTyped(json, false);
}

export function CommissionsResponseToJSONTyped(value?: CommissionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CommissionRowToJSON)),
        'total': value['total'],
        'totalAmount': value['totalAmount'],
        'totalCommission': value['totalCommission'],
    };
}

