/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBrokerOrderRequest
 */
export interface CreateBrokerOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateBrokerOrderRequest
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBrokerOrderRequest
     */
    issuanceId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateBrokerOrderRequest
     */
    amount: number;
}

/**
 * Check if a given object implements the CreateBrokerOrderRequest interface.
 */
export function instanceOfCreateBrokerOrderRequest(value: object): value is CreateBrokerOrderRequest {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('issuanceId' in value) || value['issuanceId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CreateBrokerOrderRequestFromJSON(json: any): CreateBrokerOrderRequest {
    return CreateBrokerOrderRequestFromJSONTyped(json, false);
}

export function CreateBrokerOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBrokerOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['clientId'],
        'issuanceId': json['issuanceId'],
        'amount': json['amount'],
    };
}

export function CreateBrokerOrderRequestToJSON(json: any): CreateBrokerOrderRequest {
    return CreateBrokerOrderRequestToJSONTyped(json, false);
}

export function CreateBrokerOrderRequestToJSONTyped(value?: CreateBrokerOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientId': value['clientId'],
        'issuanceId': value['issuanceId'],
        'amount': value['amount'],
    };
}

