/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedItem
 */
export interface FeedItem {
    /**
     * 
     * @type {string}
     * @memberof FeedItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FeedItem
     */
    type: FeedItemTypeEnum;
    /**
     * Event title
     * @type {string}
     * @memberof FeedItem
     */
    title?: string;
    /**
     * Event description
     * @type {string}
     * @memberof FeedItem
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedItem
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedItem
     */
    clientName?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedItem
     */
    issuanceId?: string;
    /**
     * 
     * @type {number}
     * @memberof FeedItem
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof FeedItem
     */
    status?: FeedItemStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof FeedItem
     */
    timestamp: Date;
    /**
     * Additional event data
     * @type {{ [key: string]: any; }}
     * @memberof FeedItem
     */
    metadata?: { [key: string]: any; };
}


/**
 * @export
 */
export const FeedItemTypeEnum = {
    Order: 'order',
    Transfer: 'transfer',
    Payout: 'payout',
    Kyc: 'kyc',
    Qualification: 'qualification'
} as const;
export type FeedItemTypeEnum = typeof FeedItemTypeEnum[keyof typeof FeedItemTypeEnum];

/**
 * @export
 */
export const FeedItemStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type FeedItemStatusEnum = typeof FeedItemStatusEnum[keyof typeof FeedItemStatusEnum];


/**
 * Check if a given object implements the FeedItem interface.
 */
export function instanceOfFeedItem(value: object): value is FeedItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function FeedItemFromJSON(json: any): FeedItem {
    return FeedItemFromJSONTyped(json, false);
}

export function FeedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'clientName': json['clientName'] == null ? undefined : json['clientName'],
        'issuanceId': json['issuanceId'] == null ? undefined : json['issuanceId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'status': json['status'] == null ? undefined : json['status'],
        'timestamp': (new Date(json['timestamp'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function FeedItemToJSON(json: any): FeedItem {
    return FeedItemToJSONTyped(json, false);
}

export function FeedItemToJSONTyped(value?: FeedItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'title': value['title'],
        'description': value['description'],
        'clientId': value['clientId'],
        'clientName': value['clientName'],
        'issuanceId': value['issuanceId'],
        'amount': value['amount'],
        'status': value['status'],
        'timestamp': value['timestamp'].toISOString(),
        'metadata': value['metadata'],
    };
}

