/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Holding
 */
export interface Holding {
    /**
     * 
     * @type {string}
     * @memberof Holding
     */
    assetId?: string;
    /**
     * 
     * @type {string}
     * @memberof Holding
     */
    assetCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Holding
     */
    assetName?: string;
    /**
     * 
     * @type {number}
     * @memberof Holding
     */
    amount?: number;
}

/**
 * Check if a given object implements the Holding interface.
 */
export function instanceOfHolding(value: object): value is Holding {
    return true;
}

export function HoldingFromJSON(json: any): Holding {
    return HoldingFromJSONTyped(json, false);
}

export function HoldingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Holding {
    if (json == null) {
        return json;
    }
    return {
        
        'assetId': json['assetId'] == null ? undefined : json['assetId'],
        'assetCode': json['assetCode'] == null ? undefined : json['assetCode'],
        'assetName': json['assetName'] == null ? undefined : json['assetName'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function HoldingToJSON(json: any): Holding {
    return HoldingToJSONTyped(json, false);
}

export function HoldingToJSONTyped(value?: Holding | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assetId': value['assetId'],
        'assetCode': value['assetCode'],
        'assetName': value['assetName'],
        'amount': value['amount'],
    };
}

