/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvestorStatusResponse
 */
export interface InvestorStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof InvestorStatusResponse
     */
    investorId: string;
    /**
     * 
     * @type {string}
     * @memberof InvestorStatusResponse
     */
    kyc: InvestorStatusResponseKycEnum;
    /**
     * 
     * @type {string}
     * @memberof InvestorStatusResponse
     */
    qualificationTier: InvestorStatusResponseQualificationTierEnum;
    /**
     * 
     * @type {number}
     * @memberof InvestorStatusResponse
     */
    qualificationLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof InvestorStatusResponse
     */
    qualificationUsed?: number;
    /**
     * 
     * @type {Date}
     * @memberof InvestorStatusResponse
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const InvestorStatusResponseKycEnum = {
    Pass: 'pass',
    Fail: 'fail',
    Pending: 'pending',
    Review: 'review'
} as const;
export type InvestorStatusResponseKycEnum = typeof InvestorStatusResponseKycEnum[keyof typeof InvestorStatusResponseKycEnum];

/**
 * @export
 */
export const InvestorStatusResponseQualificationTierEnum = {
    Unqualified: 'unqualified',
    Qualified: 'qualified',
    Professional: 'professional'
} as const;
export type InvestorStatusResponseQualificationTierEnum = typeof InvestorStatusResponseQualificationTierEnum[keyof typeof InvestorStatusResponseQualificationTierEnum];


/**
 * Check if a given object implements the InvestorStatusResponse interface.
 */
export function instanceOfInvestorStatusResponse(value: object): value is InvestorStatusResponse {
    if (!('investorId' in value) || value['investorId'] === undefined) return false;
    if (!('kyc' in value) || value['kyc'] === undefined) return false;
    if (!('qualificationTier' in value) || value['qualificationTier'] === undefined) return false;
    return true;
}

export function InvestorStatusResponseFromJSON(json: any): InvestorStatusResponse {
    return InvestorStatusResponseFromJSONTyped(json, false);
}

export function InvestorStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvestorStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'investorId': json['investorId'],
        'kyc': json['kyc'],
        'qualificationTier': json['qualificationTier'],
        'qualificationLimit': json['qualificationLimit'] == null ? undefined : json['qualificationLimit'],
        'qualificationUsed': json['qualificationUsed'] == null ? undefined : json['qualificationUsed'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function InvestorStatusResponseToJSON(json: any): InvestorStatusResponse {
    return InvestorStatusResponseToJSONTyped(json, false);
}

export function InvestorStatusResponseToJSONTyped(value?: InvestorStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'investorId': value['investorId'],
        'kyc': value['kyc'],
        'qualificationTier': value['qualificationTier'],
        'qualificationLimit': value['qualificationLimit'],
        'qualificationUsed': value['qualificationUsed'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

