/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssuerIssuancesReportResponseSummary
 */
export interface IssuerIssuancesReportResponseSummary {
    /**
     * 
     * @type {number}
     * @memberof IssuerIssuancesReportResponseSummary
     */
    totalIssuances?: number;
    /**
     * 
     * @type {number}
     * @memberof IssuerIssuancesReportResponseSummary
     */
    totalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof IssuerIssuancesReportResponseSummary
     */
    totalSold?: number;
    /**
     * 
     * @type {number}
     * @memberof IssuerIssuancesReportResponseSummary
     */
    totalInvestors?: number;
}

/**
 * Check if a given object implements the IssuerIssuancesReportResponseSummary interface.
 */
export function instanceOfIssuerIssuancesReportResponseSummary(value: object): value is IssuerIssuancesReportResponseSummary {
    return true;
}

export function IssuerIssuancesReportResponseSummaryFromJSON(json: any): IssuerIssuancesReportResponseSummary {
    return IssuerIssuancesReportResponseSummaryFromJSONTyped(json, false);
}

export function IssuerIssuancesReportResponseSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuerIssuancesReportResponseSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'totalIssuances': json['totalIssuances'] == null ? undefined : json['totalIssuances'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'totalSold': json['totalSold'] == null ? undefined : json['totalSold'],
        'totalInvestors': json['totalInvestors'] == null ? undefined : json['totalInvestors'],
    };
}

export function IssuerIssuancesReportResponseSummaryToJSON(json: any): IssuerIssuancesReportResponseSummary {
    return IssuerIssuancesReportResponseSummaryToJSONTyped(json, false);
}

export function IssuerIssuancesReportResponseSummaryToJSONTyped(value?: IssuerIssuancesReportResponseSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalIssuances': value['totalIssuances'],
        'totalAmount': value['totalAmount'],
        'totalSold': value['totalSold'],
        'totalInvestors': value['totalInvestors'],
    };
}

