/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssuerPayoutsReportResponseItemsInner
 */
export interface IssuerPayoutsReportResponseItemsInner {
    /**
     * Period label (depends on granularity)
     * @type {string}
     * @memberof IssuerPayoutsReportResponseItemsInner
     */
    period?: string;
    /**
     * 
     * @type {number}
     * @memberof IssuerPayoutsReportResponseItemsInner
     */
    totalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof IssuerPayoutsReportResponseItemsInner
     */
    payoutCount?: number;
    /**
     * 
     * @type {number}
     * @memberof IssuerPayoutsReportResponseItemsInner
     */
    investorsCount?: number;
}

/**
 * Check if a given object implements the IssuerPayoutsReportResponseItemsInner interface.
 */
export function instanceOfIssuerPayoutsReportResponseItemsInner(value: object): value is IssuerPayoutsReportResponseItemsInner {
    return true;
}

export function IssuerPayoutsReportResponseItemsInnerFromJSON(json: any): IssuerPayoutsReportResponseItemsInner {
    return IssuerPayoutsReportResponseItemsInnerFromJSONTyped(json, false);
}

export function IssuerPayoutsReportResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuerPayoutsReportResponseItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'period': json['period'] == null ? undefined : json['period'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'payoutCount': json['payoutCount'] == null ? undefined : json['payoutCount'],
        'investorsCount': json['investorsCount'] == null ? undefined : json['investorsCount'],
    };
}

export function IssuerPayoutsReportResponseItemsInnerToJSON(json: any): IssuerPayoutsReportResponseItemsInner {
    return IssuerPayoutsReportResponseItemsInnerToJSONTyped(json, false);
}

export function IssuerPayoutsReportResponseItemsInnerToJSONTyped(value?: IssuerPayoutsReportResponseItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': value['period'],
        'totalAmount': value['totalAmount'],
        'payoutCount': value['payoutCount'],
        'investorsCount': value['investorsCount'],
    };
}

