/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssuerReportRow
 */
export interface IssuerReportRow {
    /**
     * 
     * @type {string}
     * @memberof IssuerReportRow
     */
    issuanceId?: string;
    /**
     * 
     * @type {string}
     * @memberof IssuerReportRow
     */
    assetCode?: string;
    /**
     * 
     * @type {string}
     * @memberof IssuerReportRow
     */
    assetName?: string;
    /**
     * 
     * @type {number}
     * @memberof IssuerReportRow
     */
    totalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof IssuerReportRow
     */
    soldAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof IssuerReportRow
     */
    investorsCount?: number;
    /**
     * 
     * @type {string}
     * @memberof IssuerReportRow
     */
    status?: IssuerReportRowStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof IssuerReportRow
     */
    issueDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IssuerReportRow
     */
    maturityDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IssuerReportRow
     */
    publishedAt?: Date;
}


/**
 * @export
 */
export const IssuerReportRowStatusEnum = {
    Draft: 'draft',
    Published: 'published',
    Closed: 'closed',
    Redeemed: 'redeemed'
} as const;
export type IssuerReportRowStatusEnum = typeof IssuerReportRowStatusEnum[keyof typeof IssuerReportRowStatusEnum];


/**
 * Check if a given object implements the IssuerReportRow interface.
 */
export function instanceOfIssuerReportRow(value: object): value is IssuerReportRow {
    return true;
}

export function IssuerReportRowFromJSON(json: any): IssuerReportRow {
    return IssuerReportRowFromJSONTyped(json, false);
}

export function IssuerReportRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuerReportRow {
    if (json == null) {
        return json;
    }
    return {
        
        'issuanceId': json['issuanceId'] == null ? undefined : json['issuanceId'],
        'assetCode': json['assetCode'] == null ? undefined : json['assetCode'],
        'assetName': json['assetName'] == null ? undefined : json['assetName'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'soldAmount': json['soldAmount'] == null ? undefined : json['soldAmount'],
        'investorsCount': json['investorsCount'] == null ? undefined : json['investorsCount'],
        'status': json['status'] == null ? undefined : json['status'],
        'issueDate': json['issueDate'] == null ? undefined : (new Date(json['issueDate'])),
        'maturityDate': json['maturityDate'] == null ? undefined : (new Date(json['maturityDate'])),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
    };
}

export function IssuerReportRowToJSON(json: any): IssuerReportRow {
    return IssuerReportRowToJSONTyped(json, false);
}

export function IssuerReportRowToJSONTyped(value?: IssuerReportRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issuanceId': value['issuanceId'],
        'assetCode': value['assetCode'],
        'assetName': value['assetName'],
        'totalAmount': value['totalAmount'],
        'soldAmount': value['soldAmount'],
        'investorsCount': value['investorsCount'],
        'status': value['status'],
        'issueDate': value['issueDate'] == null ? value['issueDate'] : value['issueDate'].toISOString().substring(0,10),
        'maturityDate': value['maturityDate'] == null ? value['maturityDate'] : value['maturityDate'].toISOString().substring(0,10),
        'publishedAt': value['publishedAt'] == null ? value['publishedAt'] : value['publishedAt'].toISOString(),
    };
}

