/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KycDocument
 */
export interface KycDocument {
    /**
     * 
     * @type {string}
     * @memberof KycDocument
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof KycDocument
     */
    investorId?: string;
    /**
     * 
     * @type {string}
     * @memberof KycDocument
     */
    documentType?: KycDocumentDocumentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof KycDocument
     */
    fileName?: string;
    /**
     * File size in bytes
     * @type {number}
     * @memberof KycDocument
     */
    fileSize?: number;
    /**
     * 
     * @type {string}
     * @memberof KycDocument
     */
    mimeType?: string;
    /**
     * S3/MinIO storage URL
     * @type {string}
     * @memberof KycDocument
     */
    storageUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof KycDocument
     */
    uploadedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof KycDocument
     */
    uploadedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof KycDocument
     */
    comment?: string;
}


/**
 * @export
 */
export const KycDocumentDocumentTypeEnum = {
    Passport: 'passport',
    Inn: 'inn',
    Snils: 'snils',
    AddressProof: 'address_proof',
    IncomeProof: 'income_proof',
    Other: 'other'
} as const;
export type KycDocumentDocumentTypeEnum = typeof KycDocumentDocumentTypeEnum[keyof typeof KycDocumentDocumentTypeEnum];


/**
 * Check if a given object implements the KycDocument interface.
 */
export function instanceOfKycDocument(value: object): value is KycDocument {
    return true;
}

export function KycDocumentFromJSON(json: any): KycDocument {
    return KycDocumentFromJSONTyped(json, false);
}

export function KycDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): KycDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'investorId': json['investorId'] == null ? undefined : json['investorId'],
        'documentType': json['documentType'] == null ? undefined : json['documentType'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'fileSize': json['fileSize'] == null ? undefined : json['fileSize'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'storageUrl': json['storageUrl'] == null ? undefined : json['storageUrl'],
        'uploadedAt': json['uploadedAt'] == null ? undefined : (new Date(json['uploadedAt'])),
        'uploadedBy': json['uploadedBy'] == null ? undefined : json['uploadedBy'],
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function KycDocumentToJSON(json: any): KycDocument {
    return KycDocumentToJSONTyped(json, false);
}

export function KycDocumentToJSONTyped(value?: KycDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'investorId': value['investorId'],
        'documentType': value['documentType'],
        'fileName': value['fileName'],
        'fileSize': value['fileSize'],
        'mimeType': value['mimeType'],
        'storageUrl': value['storageUrl'],
        'uploadedAt': value['uploadedAt'] == null ? value['uploadedAt'] : value['uploadedAt'].toISOString(),
        'uploadedBy': value['uploadedBy'],
        'comment': value['comment'],
    };
}

