/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KycDecisionRequest
 */
export interface KycDecisionRequest {
    /**
     * KYC decision status
     * @type {string}
     * @memberof KycDecisionRequest
     */
    status: KycDecisionRequestStatusEnum;
    /**
     * Decision comment/reason
     * @type {string}
     * @memberof KycDecisionRequest
     */
    comment: string;
}


/**
 * @export
 */
export const KycDecisionRequestStatusEnum = {
    Approved: 'approved',
    Rejected: 'rejected'
} as const;
export type KycDecisionRequestStatusEnum = typeof KycDecisionRequestStatusEnum[keyof typeof KycDecisionRequestStatusEnum];


/**
 * Check if a given object implements the KycDecisionRequest interface.
 */
export function instanceOfKycDecisionRequest(value: object): value is KycDecisionRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function KycDecisionRequestFromJSON(json: any): KycDecisionRequest {
    return KycDecisionRequestFromJSONTyped(json, false);
}

export function KycDecisionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KycDecisionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'comment': json['comment'],
    };
}

export function KycDecisionRequestToJSON(json: any): KycDecisionRequest {
    return KycDecisionRequestToJSONTyped(json, false);
}

export function KycDecisionRequestToJSONTyped(value?: KycDecisionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'comment': value['comment'],
    };
}

