/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KycDecisionResponse
 */
export interface KycDecisionResponse {
    /**
     * 
     * @type {string}
     * @memberof KycDecisionResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof KycDecisionResponse
     */
    investorId?: string;
    /**
     * 
     * @type {string}
     * @memberof KycDecisionResponse
     */
    status?: KycDecisionResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof KycDecisionResponse
     */
    comment?: string;
    /**
     * User who made the decision
     * @type {string}
     * @memberof KycDecisionResponse
     */
    decisionBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof KycDecisionResponse
     */
    decisionAt?: Date;
}


/**
 * @export
 */
export const KycDecisionResponseStatusEnum = {
    Approved: 'approved',
    Rejected: 'rejected'
} as const;
export type KycDecisionResponseStatusEnum = typeof KycDecisionResponseStatusEnum[keyof typeof KycDecisionResponseStatusEnum];


/**
 * Check if a given object implements the KycDecisionResponse interface.
 */
export function instanceOfKycDecisionResponse(value: object): value is KycDecisionResponse {
    return true;
}

export function KycDecisionResponseFromJSON(json: any): KycDecisionResponse {
    return KycDecisionResponseFromJSONTyped(json, false);
}

export function KycDecisionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KycDecisionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'investorId': json['investorId'] == null ? undefined : json['investorId'],
        'status': json['status'] == null ? undefined : json['status'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'decisionBy': json['decisionBy'] == null ? undefined : json['decisionBy'],
        'decisionAt': json['decisionAt'] == null ? undefined : (new Date(json['decisionAt'])),
    };
}

export function KycDecisionResponseToJSON(json: any): KycDecisionResponse {
    return KycDecisionResponseToJSONTyped(json, false);
}

export function KycDecisionResponseToJSONTyped(value?: KycDecisionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'investorId': value['investorId'],
        'status': value['status'],
        'comment': value['comment'],
        'decisionBy': value['decisionBy'],
        'decisionAt': value['decisionAt'] == null ? value['decisionAt'] : value['decisionAt'].toISOString(),
    };
}

