/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KycResult
 */
export interface KycResult {
    /**
     * 
     * @type {string}
     * @memberof KycResult
     */
    investorId: string;
    /**
     * 
     * @type {string}
     * @memberof KycResult
     */
    status: KycResultStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof KycResult
     */
    checkedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof KycResult
     */
    reason?: string;
}


/**
 * @export
 */
export const KycResultStatusEnum = {
    Pass: 'pass',
    Fail: 'fail',
    Pending: 'pending',
    Review: 'review'
} as const;
export type KycResultStatusEnum = typeof KycResultStatusEnum[keyof typeof KycResultStatusEnum];


/**
 * Check if a given object implements the KycResult interface.
 */
export function instanceOfKycResult(value: object): value is KycResult {
    if (!('investorId' in value) || value['investorId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function KycResultFromJSON(json: any): KycResult {
    return KycResultFromJSONTyped(json, false);
}

export function KycResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): KycResult {
    if (json == null) {
        return json;
    }
    return {
        
        'investorId': json['investorId'],
        'status': json['status'],
        'checkedAt': json['checkedAt'] == null ? undefined : (new Date(json['checkedAt'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function KycResultToJSON(json: any): KycResult {
    return KycResultToJSONTyped(json, false);
}

export function KycResultToJSONTyped(value?: KycResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'investorId': value['investorId'],
        'status': value['status'],
        'checkedAt': value['checkedAt'] == null ? value['checkedAt'] : value['checkedAt'].toISOString(),
        'reason': value['reason'],
    };
}

