/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayoutItem
 */
export interface PayoutItem {
    /**
     * 
     * @type {string}
     * @memberof PayoutItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PayoutItem
     */
    batchId?: string;
    /**
     * 
     * @type {string}
     * @memberof PayoutItem
     */
    issuanceId?: string;
    /**
     * 
     * @type {string}
     * @memberof PayoutItem
     */
    investorId?: string;
    /**
     * 
     * @type {number}
     * @memberof PayoutItem
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof PayoutItem
     */
    status?: PayoutItemStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof PayoutItem
     */
    executedAt?: Date;
}


/**
 * @export
 */
export const PayoutItemStatusEnum = {
    Pending: 'pending',
    Executed: 'executed',
    Failed: 'failed'
} as const;
export type PayoutItemStatusEnum = typeof PayoutItemStatusEnum[keyof typeof PayoutItemStatusEnum];


/**
 * Check if a given object implements the PayoutItem interface.
 */
export function instanceOfPayoutItem(value: object): value is PayoutItem {
    return true;
}

export function PayoutItemFromJSON(json: any): PayoutItem {
    return PayoutItemFromJSONTyped(json, false);
}

export function PayoutItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayoutItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'batchId': json['batchId'] == null ? undefined : json['batchId'],
        'issuanceId': json['issuanceId'] == null ? undefined : json['issuanceId'],
        'investorId': json['investorId'] == null ? undefined : json['investorId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'status': json['status'] == null ? undefined : json['status'],
        'executedAt': json['executedAt'] == null ? undefined : (new Date(json['executedAt'])),
    };
}

export function PayoutItemToJSON(json: any): PayoutItem {
    return PayoutItemToJSONTyped(json, false);
}

export function PayoutItemToJSONTyped(value?: PayoutItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'batchId': value['batchId'],
        'issuanceId': value['issuanceId'],
        'investorId': value['investorId'],
        'amount': value['amount'],
        'status': value['status'],
        'executedAt': value['executedAt'] == null ? value['executedAt'] : value['executedAt'].toISOString(),
    };
}

