/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RedeemRequest
 */
export interface RedeemRequest {
    /**
     * 
     * @type {number}
     * @memberof RedeemRequest
     */
    amount: number;
}

/**
 * Check if a given object implements the RedeemRequest interface.
 */
export function instanceOfRedeemRequest(value: object): value is RedeemRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function RedeemRequestFromJSON(json: any): RedeemRequest {
    return RedeemRequestFromJSONTyped(json, false);
}

export function RedeemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedeemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
    };
}

export function RedeemRequestToJSON(json: any): RedeemRequest {
    return RedeemRequestToJSONTyped(json, false);
}

export function RedeemRequestToJSONTyped(value?: RedeemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
    };
}

