/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TxHistoryItem } from './TxHistoryItem';
import {
    TxHistoryItemFromJSON,
    TxHistoryItemFromJSONTyped,
    TxHistoryItemToJSON,
    TxHistoryItemToJSONTyped,
} from './TxHistoryItem';

/**
 * 
 * @export
 * @interface TransactionHistoryResponse
 */
export interface TransactionHistoryResponse {
    /**
     * 
     * @type {Array<TxHistoryItem>}
     * @memberof TransactionHistoryResponse
     */
    items?: Array<TxHistoryItem>;
    /**
     * 
     * @type {number}
     * @memberof TransactionHistoryResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the TransactionHistoryResponse interface.
 */
export function instanceOfTransactionHistoryResponse(value: object): value is TransactionHistoryResponse {
    return true;
}

export function TransactionHistoryResponseFromJSON(json: any): TransactionHistoryResponse {
    return TransactionHistoryResponseFromJSONTyped(json, false);
}

export function TransactionHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TxHistoryItemFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function TransactionHistoryResponseToJSON(json: any): TransactionHistoryResponse {
    return TransactionHistoryResponseToJSONTyped(json, false);
}

export function TransactionHistoryResponseToJSONTyped(value?: TransactionHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(TxHistoryItemToJSON)),
        'total': value['total'],
    };
}

