/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TxHistoryItem
 */
export interface TxHistoryItem {
    /**
     * 
     * @type {string}
     * @memberof TxHistoryItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TxHistoryItem
     */
    type?: TxHistoryItemTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TxHistoryItem
     */
    issuanceId?: string;
    /**
     * 
     * @type {string}
     * @memberof TxHistoryItem
     */
    issuanceCode?: string;
    /**
     * 
     * @type {number}
     * @memberof TxHistoryItem
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof TxHistoryItem
     */
    status?: TxHistoryItemStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TxHistoryItem
     */
    dltTxHash?: string;
    /**
     * 
     * @type {Date}
     * @memberof TxHistoryItem
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TxHistoryItem
     */
    confirmedAt?: Date;
}


/**
 * @export
 */
export const TxHistoryItemTypeEnum = {
    Transfer: 'transfer',
    Redeem: 'redeem',
    Issue: 'issue'
} as const;
export type TxHistoryItemTypeEnum = typeof TxHistoryItemTypeEnum[keyof typeof TxHistoryItemTypeEnum];

/**
 * @export
 */
export const TxHistoryItemStatusEnum = {
    Pending: 'pending',
    Confirmed: 'confirmed',
    Failed: 'failed'
} as const;
export type TxHistoryItemStatusEnum = typeof TxHistoryItemStatusEnum[keyof typeof TxHistoryItemStatusEnum];


/**
 * Check if a given object implements the TxHistoryItem interface.
 */
export function instanceOfTxHistoryItem(value: object): value is TxHistoryItem {
    return true;
}

export function TxHistoryItemFromJSON(json: any): TxHistoryItem {
    return TxHistoryItemFromJSONTyped(json, false);
}

export function TxHistoryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TxHistoryItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'issuanceId': json['issuanceId'] == null ? undefined : json['issuanceId'],
        'issuanceCode': json['issuanceCode'] == null ? undefined : json['issuanceCode'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'status': json['status'] == null ? undefined : json['status'],
        'dltTxHash': json['dltTxHash'] == null ? undefined : json['dltTxHash'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'confirmedAt': json['confirmedAt'] == null ? undefined : (new Date(json['confirmedAt'])),
    };
}

export function TxHistoryItemToJSON(json: any): TxHistoryItem {
    return TxHistoryItemToJSONTyped(json, false);
}

export function TxHistoryItemToJSONTyped(value?: TxHistoryItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'issuanceId': value['issuanceId'],
        'issuanceCode': value['issuanceCode'],
        'amount': value['amount'],
        'status': value['status'],
        'dltTxHash': value['dltTxHash'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'confirmedAt': value['confirmedAt'] == null ? value['confirmedAt'] : value['confirmedAt'].toISOString(),
    };
}

