/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Client
{
    /// <summary>
    /// Provides hosting configuration for Org.OpenAPITools
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new AuditEventJsonConverter());
            _jsonOptions.Converters.Add(new AuditEventsResponseJsonConverter());
            _jsonOptions.Converters.Add(new BrokerClientJsonConverter());
            _jsonOptions.Converters.Add(new BrokerClientsResponseJsonConverter());
            _jsonOptions.Converters.Add(new BrokerOrderResponseJsonConverter());
            _jsonOptions.Converters.Add(new CommissionRowJsonConverter());
            _jsonOptions.Converters.Add(new CommissionsResponseJsonConverter());
            _jsonOptions.Converters.Add(new ComplaintResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateBrokerOrderRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateComplaintRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateIssuanceRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateOrderRequestJsonConverter());
            _jsonOptions.Converters.Add(new FeedItemJsonConverter());
            _jsonOptions.Converters.Add(new FeedResponseJsonConverter());
            _jsonOptions.Converters.Add(new HealthStatusJsonConverter());
            _jsonOptions.Converters.Add(new HoldingJsonConverter());
            _jsonOptions.Converters.Add(new InvestorStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new IssuanceResponseJsonConverter());
            _jsonOptions.Converters.Add(new IssuerIssuancesReportResponseJsonConverter());
            _jsonOptions.Converters.Add(new IssuerIssuancesReportResponseSummaryJsonConverter());
            _jsonOptions.Converters.Add(new IssuerPayoutsReportResponseJsonConverter());
            _jsonOptions.Converters.Add(new IssuerPayoutsReportResponseItemsInnerJsonConverter());
            _jsonOptions.Converters.Add(new IssuerPayoutsReportResponseSummaryJsonConverter());
            _jsonOptions.Converters.Add(new IssuerReportRowJsonConverter());
            _jsonOptions.Converters.Add(new KycCheckRequestJsonConverter());
            _jsonOptions.Converters.Add(new KycDecisionRequestJsonConverter());
            _jsonOptions.Converters.Add(new KycDecisionResponseJsonConverter());
            _jsonOptions.Converters.Add(new KycDocumentJsonConverter());
            _jsonOptions.Converters.Add(new KycDocumentsResponseJsonConverter());
            _jsonOptions.Converters.Add(new KycResultJsonConverter());
            _jsonOptions.Converters.Add(new MarketIssuanceCardJsonConverter());
            _jsonOptions.Converters.Add(new MarketIssuancesResponseJsonConverter());
            _jsonOptions.Converters.Add(new OrderResponseJsonConverter());
            _jsonOptions.Converters.Add(new PayoutHistoryResponseJsonConverter());
            _jsonOptions.Converters.Add(new PayoutItemJsonConverter());
            _jsonOptions.Converters.Add(new PayoutsReportResponseJsonConverter());
            _jsonOptions.Converters.Add(new PayoutsReportResponsePeriodJsonConverter());
            _jsonOptions.Converters.Add(new ProblemDetailsJsonConverter());
            _jsonOptions.Converters.Add(new QualificationEvaluateRequestJsonConverter());
            _jsonOptions.Converters.Add(new QualificationResultJsonConverter());
            _jsonOptions.Converters.Add(new RedeemRequestJsonConverter());
            _jsonOptions.Converters.Add(new RedeemResponseJsonConverter());
            _jsonOptions.Converters.Add(new SettlementResponseJsonConverter());
            _jsonOptions.Converters.Add(new TransactionHistoryResponseJsonConverter());
            _jsonOptions.Converters.Add(new TxHistoryItemJsonConverter());
            _jsonOptions.Converters.Add(new WalletResponseJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<AuditApiEvents>();
            _services.AddSingleton<ComplaintsApiEvents>();
            _services.AddSingleton<ComplianceApiEvents>();
            _services.AddSingleton<HealthApiEvents>();
            _services.AddSingleton<InvestorsApiEvents>();
            _services.AddSingleton<IssuancesApiEvents>();
            _services.AddSingleton<MarketApiEvents>();
            _services.AddSingleton<OrdersApiEvents>();
            _services.AddSingleton<ReportsApiEvents>();
            _services.AddSingleton<SettlementApiEvents>();
            _services.AddSingleton<WalletsApiEvents>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients
        (
            Action<HttpClient>? client = null, Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = c => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IAuditApi, AuditApi>(client));
            builders.Add(_services.AddHttpClient<IComplaintsApi, ComplaintsApi>(client));
            builders.Add(_services.AddHttpClient<IComplianceApi, ComplianceApi>(client));
            builders.Add(_services.AddHttpClient<IHealthApi, HealthApi>(client));
            builders.Add(_services.AddHttpClient<IInvestorsApi, InvestorsApi>(client));
            builders.Add(_services.AddHttpClient<IIssuancesApi, IssuancesApi>(client));
            builders.Add(_services.AddHttpClient<IMarketApi, MarketApi>(client));
            builders.Add(_services.AddHttpClient<IOrdersApi, OrdersApi>(client));
            builders.Add(_services.AddHttpClient<IReportsApi, ReportsApi>(client));
            builders.Add(_services.AddHttpClient<ISettlementApi, SettlementApi>(client));
            builders.Add(_services.AddHttpClient<IWalletsApi, WalletsApi>(client));
            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
