// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AuditEvent
    /// </summary>
    public partial class AuditEvent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuditEvent" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="actor">User/system that performed the action</param>
        /// <param name="action">Action type (e.g., &#39;create&#39;, &#39;update&#39;, &#39;delete&#39;, &#39;approve&#39;, &#39;reject&#39;)</param>
        /// <param name="entity">Entity type (e.g., &#39;issuance&#39;, &#39;order&#39;, &#39;kyc&#39;, &#39;investor&#39;)</param>
        /// <param name="timestamp">timestamp</param>
        /// <param name="actorName">Actor name or identifier</param>
        /// <param name="entityId">Entity ID</param>
        /// <param name="payload">Additional event data</param>
        /// <param name="ip">IP address</param>
        /// <param name="userAgent">User agent string</param>
        /// <param name="result">Action result</param>
        [JsonConstructor]
        public AuditEvent(Guid id, Guid actor, string action, string entity, DateTime timestamp, Option<string?> actorName = default, Option<Guid?> entityId = default, Option<Dictionary<string, Object>?> payload = default, Option<string?> ip = default, Option<string?> userAgent = default, Option<ResultEnum?> result = default)
        {
            Id = id;
            Actor = actor;
            Action = action;
            Entity = entity;
            Timestamp = timestamp;
            ActorNameOption = actorName;
            EntityIdOption = entityId;
            PayloadOption = payload;
            IpOption = ip;
            UserAgentOption = userAgent;
            ResultOption = result;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Action result
        /// </summary>
        /// <value>Action result</value>
        public enum ResultEnum
        {
            /// <summary>
            /// Enum Success for value: success
            /// </summary>
            Success = 1,

            /// <summary>
            /// Enum Failure for value: failure
            /// </summary>
            Failure = 2,

            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            Pending = 3
        }

        /// <summary>
        /// Returns a <see cref="ResultEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ResultEnum ResultEnumFromString(string value)
        {
            if (value.Equals("success"))
                return ResultEnum.Success;

            if (value.Equals("failure"))
                return ResultEnum.Failure;

            if (value.Equals("pending"))
                return ResultEnum.Pending;

            throw new NotImplementedException($"Could not convert value to type ResultEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ResultEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ResultEnum? ResultEnumFromStringOrDefault(string value)
        {
            if (value.Equals("success"))
                return ResultEnum.Success;

            if (value.Equals("failure"))
                return ResultEnum.Failure;

            if (value.Equals("pending"))
                return ResultEnum.Pending;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ResultEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ResultEnumToJsonValue(ResultEnum? value)
        {
            if (value == ResultEnum.Success)
                return "success";

            if (value == ResultEnum.Failure)
                return "failure";

            if (value == ResultEnum.Pending)
                return "pending";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Result
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ResultEnum?> ResultOption { get; private set; }

        /// <summary>
        /// Action result
        /// </summary>
        /// <value>Action result</value>
        [JsonPropertyName("result")]
        public ResultEnum? Result { get { return this.ResultOption; } set { this.ResultOption = new(value); } }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// User/system that performed the action
        /// </summary>
        /// <value>User/system that performed the action</value>
        [JsonPropertyName("actor")]
        public Guid Actor { get; set; }

        /// <summary>
        /// Action type (e.g., &#39;create&#39;, &#39;update&#39;, &#39;delete&#39;, &#39;approve&#39;, &#39;reject&#39;)
        /// </summary>
        /// <value>Action type (e.g., &#39;create&#39;, &#39;update&#39;, &#39;delete&#39;, &#39;approve&#39;, &#39;reject&#39;)</value>
        [JsonPropertyName("action")]
        public string Action { get; set; }

        /// <summary>
        /// Entity type (e.g., &#39;issuance&#39;, &#39;order&#39;, &#39;kyc&#39;, &#39;investor&#39;)
        /// </summary>
        /// <value>Entity type (e.g., &#39;issuance&#39;, &#39;order&#39;, &#39;kyc&#39;, &#39;investor&#39;)</value>
        [JsonPropertyName("entity")]
        public string Entity { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Used to track the state of ActorName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ActorNameOption { get; private set; }

        /// <summary>
        /// Actor name or identifier
        /// </summary>
        /// <value>Actor name or identifier</value>
        [JsonPropertyName("actorName")]
        public string? ActorName { get { return this.ActorNameOption; } set { this.ActorNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of EntityId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> EntityIdOption { get; private set; }

        /// <summary>
        /// Entity ID
        /// </summary>
        /// <value>Entity ID</value>
        [JsonPropertyName("entityId")]
        public Guid? EntityId { get { return this.EntityIdOption; } set { this.EntityIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Payload
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>?> PayloadOption { get; private set; }

        /// <summary>
        /// Additional event data
        /// </summary>
        /// <value>Additional event data</value>
        [JsonPropertyName("payload")]
        public Dictionary<string, Object>? Payload { get { return this.PayloadOption; } set { this.PayloadOption = new(value); } }

        /// <summary>
        /// Used to track the state of Ip
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IpOption { get; private set; }

        /// <summary>
        /// IP address
        /// </summary>
        /// <value>IP address</value>
        [JsonPropertyName("ip")]
        public string? Ip { get { return this.IpOption; } set { this.IpOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserAgent
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserAgentOption { get; private set; }

        /// <summary>
        /// User agent string
        /// </summary>
        /// <value>User agent string</value>
        [JsonPropertyName("userAgent")]
        public string? UserAgent { get { return this.UserAgentOption; } set { this.UserAgentOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuditEvent {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Actor: ").Append(Actor).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Entity: ").Append(Entity).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  ActorName: ").Append(ActorName).Append("\n");
            sb.Append("  EntityId: ").Append(EntityId).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("  Ip: ").Append(Ip).Append("\n");
            sb.Append("  UserAgent: ").Append(UserAgent).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AuditEvent" />
    /// </summary>
    public class AuditEventJsonConverter : JsonConverter<AuditEvent>
    {
        /// <summary>
        /// The format to use to serialize Timestamp
        /// </summary>
        public static string TimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="AuditEvent" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AuditEvent Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> actor = default;
            Option<string?> action = default;
            Option<string?> entity = default;
            Option<DateTime?> timestamp = default;
            Option<string?> actorName = default;
            Option<Guid?> entityId = default;
            Option<Dictionary<string, Object>?> payload = default;
            Option<string?> ip = default;
            Option<string?> userAgent = default;
            Option<AuditEvent.ResultEnum?> result = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "actor":
                            actor = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "action":
                            action = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "entity":
                            entity = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "timestamp":
                            timestamp = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "actorName":
                            actorName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "entityId":
                            entityId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "payload":
                            payload = new Option<Dictionary<string, Object>?>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "ip":
                            ip = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "userAgent":
                            userAgent = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "result":
                            string? resultRawValue = utf8JsonReader.GetString();
                            if (resultRawValue != null)
                                result = new Option<AuditEvent.ResultEnum?>(AuditEvent.ResultEnumFromStringOrDefault(resultRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class AuditEvent.", nameof(id));

            if (!actor.IsSet)
                throw new ArgumentException("Property is required for class AuditEvent.", nameof(actor));

            if (!action.IsSet)
                throw new ArgumentException("Property is required for class AuditEvent.", nameof(action));

            if (!entity.IsSet)
                throw new ArgumentException("Property is required for class AuditEvent.", nameof(entity));

            if (!timestamp.IsSet)
                throw new ArgumentException("Property is required for class AuditEvent.", nameof(timestamp));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class AuditEvent.");

            if (actor.IsSet && actor.Value == null)
                throw new ArgumentNullException(nameof(actor), "Property is not nullable for class AuditEvent.");

            if (action.IsSet && action.Value == null)
                throw new ArgumentNullException(nameof(action), "Property is not nullable for class AuditEvent.");

            if (entity.IsSet && entity.Value == null)
                throw new ArgumentNullException(nameof(entity), "Property is not nullable for class AuditEvent.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class AuditEvent.");

            if (actorName.IsSet && actorName.Value == null)
                throw new ArgumentNullException(nameof(actorName), "Property is not nullable for class AuditEvent.");

            if (entityId.IsSet && entityId.Value == null)
                throw new ArgumentNullException(nameof(entityId), "Property is not nullable for class AuditEvent.");

            if (payload.IsSet && payload.Value == null)
                throw new ArgumentNullException(nameof(payload), "Property is not nullable for class AuditEvent.");

            if (ip.IsSet && ip.Value == null)
                throw new ArgumentNullException(nameof(ip), "Property is not nullable for class AuditEvent.");

            if (userAgent.IsSet && userAgent.Value == null)
                throw new ArgumentNullException(nameof(userAgent), "Property is not nullable for class AuditEvent.");

            if (result.IsSet && result.Value == null)
                throw new ArgumentNullException(nameof(result), "Property is not nullable for class AuditEvent.");

            return new AuditEvent(id.Value!.Value!, actor.Value!.Value!, action.Value!, entity.Value!, timestamp.Value!.Value!, actorName, entityId, payload, ip, userAgent, result);
        }

        /// <summary>
        /// Serializes a <see cref="AuditEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="auditEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AuditEvent auditEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, auditEvent, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AuditEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="auditEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AuditEvent auditEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            if (auditEvent.Action == null)
                throw new ArgumentNullException(nameof(auditEvent.Action), "Property is required for class AuditEvent.");

            if (auditEvent.Entity == null)
                throw new ArgumentNullException(nameof(auditEvent.Entity), "Property is required for class AuditEvent.");

            if (auditEvent.ActorNameOption.IsSet && auditEvent.ActorName == null)
                throw new ArgumentNullException(nameof(auditEvent.ActorName), "Property is required for class AuditEvent.");

            if (auditEvent.PayloadOption.IsSet && auditEvent.Payload == null)
                throw new ArgumentNullException(nameof(auditEvent.Payload), "Property is required for class AuditEvent.");

            if (auditEvent.IpOption.IsSet && auditEvent.Ip == null)
                throw new ArgumentNullException(nameof(auditEvent.Ip), "Property is required for class AuditEvent.");

            if (auditEvent.UserAgentOption.IsSet && auditEvent.UserAgent == null)
                throw new ArgumentNullException(nameof(auditEvent.UserAgent), "Property is required for class AuditEvent.");

            writer.WriteString("id", auditEvent.Id);

            writer.WriteString("actor", auditEvent.Actor);

            writer.WriteString("action", auditEvent.Action);

            writer.WriteString("entity", auditEvent.Entity);

            writer.WriteString("timestamp", auditEvent.Timestamp.ToString(TimestampFormat));

            if (auditEvent.ActorNameOption.IsSet)
                writer.WriteString("actorName", auditEvent.ActorName);

            if (auditEvent.EntityIdOption.IsSet)
                writer.WriteString("entityId", auditEvent.EntityIdOption.Value!.Value);

            if (auditEvent.PayloadOption.IsSet)
            {
                writer.WritePropertyName("payload");
                JsonSerializer.Serialize(writer, auditEvent.Payload, jsonSerializerOptions);
            }
            if (auditEvent.IpOption.IsSet)
                writer.WriteString("ip", auditEvent.Ip);

            if (auditEvent.UserAgentOption.IsSet)
                writer.WriteString("userAgent", auditEvent.UserAgent);

            var resultRawValue = AuditEvent.ResultEnumToJsonValue(auditEvent.ResultOption.Value!.Value);
            writer.WriteString("result", resultRawValue);
        }
    }
}
