// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CreateIssuanceRequest
    /// </summary>
    public partial class CreateIssuanceRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateIssuanceRequest" /> class.
        /// </summary>
        /// <param name="assetId">assetId</param>
        /// <param name="issuerId">issuerId</param>
        /// <param name="totalAmount">totalAmount</param>
        /// <param name="nominal">nominal</param>
        /// <param name="issueDate">issueDate</param>
        /// <param name="maturityDate">maturityDate</param>
        /// <param name="scheduleJson">Payout schedule (optional)</param>
        [JsonConstructor]
        public CreateIssuanceRequest(Guid assetId, Guid issuerId, decimal totalAmount, decimal nominal, DateOnly issueDate, DateOnly maturityDate, Option<Object?> scheduleJson = default)
        {
            AssetId = assetId;
            IssuerId = issuerId;
            TotalAmount = totalAmount;
            Nominal = nominal;
            IssueDate = issueDate;
            MaturityDate = maturityDate;
            ScheduleJsonOption = scheduleJson;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [JsonPropertyName("assetId")]
        public Guid AssetId { get; set; }

        /// <summary>
        /// Gets or Sets IssuerId
        /// </summary>
        [JsonPropertyName("issuerId")]
        public Guid IssuerId { get; set; }

        /// <summary>
        /// Gets or Sets TotalAmount
        /// </summary>
        [JsonPropertyName("totalAmount")]
        public decimal TotalAmount { get; set; }

        /// <summary>
        /// Gets or Sets Nominal
        /// </summary>
        [JsonPropertyName("nominal")]
        public decimal Nominal { get; set; }

        /// <summary>
        /// Gets or Sets IssueDate
        /// </summary>
        [JsonPropertyName("issueDate")]
        public DateOnly IssueDate { get; set; }

        /// <summary>
        /// Gets or Sets MaturityDate
        /// </summary>
        [JsonPropertyName("maturityDate")]
        public DateOnly MaturityDate { get; set; }

        /// <summary>
        /// Used to track the state of ScheduleJson
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> ScheduleJsonOption { get; private set; }

        /// <summary>
        /// Payout schedule (optional)
        /// </summary>
        /// <value>Payout schedule (optional)</value>
        [JsonPropertyName("scheduleJson")]
        public Object? ScheduleJson { get { return this.ScheduleJsonOption; } set { this.ScheduleJsonOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateIssuanceRequest {\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  IssuerId: ").Append(IssuerId).Append("\n");
            sb.Append("  TotalAmount: ").Append(TotalAmount).Append("\n");
            sb.Append("  Nominal: ").Append(Nominal).Append("\n");
            sb.Append("  IssueDate: ").Append(IssueDate).Append("\n");
            sb.Append("  MaturityDate: ").Append(MaturityDate).Append("\n");
            sb.Append("  ScheduleJson: ").Append(ScheduleJson).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TotalAmount (decimal) minimum
            if (this.TotalAmount < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for TotalAmount, must be a value greater than or equal to 0.", new [] { "TotalAmount" });
            }

            // Nominal (decimal) minimum
            if (this.Nominal < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for Nominal, must be a value greater than or equal to 0.", new [] { "Nominal" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateIssuanceRequest" />
    /// </summary>
    public class CreateIssuanceRequestJsonConverter : JsonConverter<CreateIssuanceRequest>
    {
        /// <summary>
        /// The format to use to serialize IssueDate
        /// </summary>
        public static string IssueDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize MaturityDate
        /// </summary>
        public static string MaturityDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="CreateIssuanceRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateIssuanceRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> assetId = default;
            Option<Guid?> issuerId = default;
            Option<decimal?> totalAmount = default;
            Option<decimal?> nominal = default;
            Option<DateOnly?> issueDate = default;
            Option<DateOnly?> maturityDate = default;
            Option<Object?> scheduleJson = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "assetId":
                            assetId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "issuerId":
                            issuerId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "totalAmount":
                            totalAmount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "nominal":
                            nominal = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "issueDate":
                            issueDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "maturityDate":
                            maturityDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "scheduleJson":
                            scheduleJson = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!assetId.IsSet)
                throw new ArgumentException("Property is required for class CreateIssuanceRequest.", nameof(assetId));

            if (!issuerId.IsSet)
                throw new ArgumentException("Property is required for class CreateIssuanceRequest.", nameof(issuerId));

            if (!totalAmount.IsSet)
                throw new ArgumentException("Property is required for class CreateIssuanceRequest.", nameof(totalAmount));

            if (!nominal.IsSet)
                throw new ArgumentException("Property is required for class CreateIssuanceRequest.", nameof(nominal));

            if (!issueDate.IsSet)
                throw new ArgumentException("Property is required for class CreateIssuanceRequest.", nameof(issueDate));

            if (!maturityDate.IsSet)
                throw new ArgumentException("Property is required for class CreateIssuanceRequest.", nameof(maturityDate));

            if (assetId.IsSet && assetId.Value == null)
                throw new ArgumentNullException(nameof(assetId), "Property is not nullable for class CreateIssuanceRequest.");

            if (issuerId.IsSet && issuerId.Value == null)
                throw new ArgumentNullException(nameof(issuerId), "Property is not nullable for class CreateIssuanceRequest.");

            if (totalAmount.IsSet && totalAmount.Value == null)
                throw new ArgumentNullException(nameof(totalAmount), "Property is not nullable for class CreateIssuanceRequest.");

            if (nominal.IsSet && nominal.Value == null)
                throw new ArgumentNullException(nameof(nominal), "Property is not nullable for class CreateIssuanceRequest.");

            if (issueDate.IsSet && issueDate.Value == null)
                throw new ArgumentNullException(nameof(issueDate), "Property is not nullable for class CreateIssuanceRequest.");

            if (maturityDate.IsSet && maturityDate.Value == null)
                throw new ArgumentNullException(nameof(maturityDate), "Property is not nullable for class CreateIssuanceRequest.");

            if (scheduleJson.IsSet && scheduleJson.Value == null)
                throw new ArgumentNullException(nameof(scheduleJson), "Property is not nullable for class CreateIssuanceRequest.");

            return new CreateIssuanceRequest(assetId.Value!.Value!, issuerId.Value!.Value!, totalAmount.Value!.Value!, nominal.Value!.Value!, issueDate.Value!.Value!, maturityDate.Value!.Value!, scheduleJson);
        }

        /// <summary>
        /// Serializes a <see cref="CreateIssuanceRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createIssuanceRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateIssuanceRequest createIssuanceRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createIssuanceRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateIssuanceRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createIssuanceRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateIssuanceRequest createIssuanceRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createIssuanceRequest.ScheduleJsonOption.IsSet && createIssuanceRequest.ScheduleJson == null)
                throw new ArgumentNullException(nameof(createIssuanceRequest.ScheduleJson), "Property is required for class CreateIssuanceRequest.");

            writer.WriteString("assetId", createIssuanceRequest.AssetId);

            writer.WriteString("issuerId", createIssuanceRequest.IssuerId);

            writer.WriteNumber("totalAmount", createIssuanceRequest.TotalAmount);

            writer.WriteNumber("nominal", createIssuanceRequest.Nominal);

            writer.WriteString("issueDate", createIssuanceRequest.IssueDate.ToString(IssueDateFormat));

            writer.WriteString("maturityDate", createIssuanceRequest.MaturityDate.ToString(MaturityDateFormat));

            if (createIssuanceRequest.ScheduleJsonOption.IsSet)
            {
                writer.WritePropertyName("scheduleJson");
                JsonSerializer.Serialize(writer, createIssuanceRequest.ScheduleJson, jsonSerializerOptions);
            }
        }
    }
}
