// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CreateComplaintRequest
    /// </summary>
    public partial class CreateComplaintRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateComplaintRequest" /> class.
        /// </summary>
        /// <param name="category">category</param>
        /// <param name="text">text</param>
        /// <param name="investorId">investorId</param>
        [JsonConstructor]
        public CreateComplaintRequest(CategoryEnum category, string text, Option<Guid?> investorId = default)
        {
            Category = category;
            Text = text;
            InvestorIdOption = investorId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Category
        /// </summary>
        public enum CategoryEnum
        {
            /// <summary>
            /// Enum Fraud for value: fraud
            /// </summary>
            Fraud = 1,

            /// <summary>
            /// Enum Service for value: service
            /// </summary>
            Service = 2,

            /// <summary>
            /// Enum Technical for value: technical
            /// </summary>
            Technical = 3,

            /// <summary>
            /// Enum Other for value: other
            /// </summary>
            Other = 4
        }

        /// <summary>
        /// Returns a <see cref="CategoryEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CategoryEnum CategoryEnumFromString(string value)
        {
            if (value.Equals("fraud"))
                return CategoryEnum.Fraud;

            if (value.Equals("service"))
                return CategoryEnum.Service;

            if (value.Equals("technical"))
                return CategoryEnum.Technical;

            if (value.Equals("other"))
                return CategoryEnum.Other;

            throw new NotImplementedException($"Could not convert value to type CategoryEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CategoryEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CategoryEnum? CategoryEnumFromStringOrDefault(string value)
        {
            if (value.Equals("fraud"))
                return CategoryEnum.Fraud;

            if (value.Equals("service"))
                return CategoryEnum.Service;

            if (value.Equals("technical"))
                return CategoryEnum.Technical;

            if (value.Equals("other"))
                return CategoryEnum.Other;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CategoryEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CategoryEnumToJsonValue(CategoryEnum value)
        {
            if (value == CategoryEnum.Fraud)
                return "fraud";

            if (value == CategoryEnum.Service)
                return "service";

            if (value == CategoryEnum.Technical)
                return "technical";

            if (value == CategoryEnum.Other)
                return "other";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [JsonPropertyName("category")]
        public CategoryEnum Category { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [JsonPropertyName("text")]
        public string Text { get; set; }

        /// <summary>
        /// Used to track the state of InvestorId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> InvestorIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets InvestorId
        /// </summary>
        [JsonPropertyName("investorId")]
        public Guid? InvestorId { get { return this.InvestorIdOption; } set { this.InvestorIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateComplaintRequest {\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  InvestorId: ").Append(InvestorId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Text (string) maxLength
            if (this.Text != null && this.Text.Length > 5000)
            {
                yield return new ValidationResult("Invalid value for Text, length must be less than 5000.", new [] { "Text" });
            }

            // Text (string) minLength
            if (this.Text != null && this.Text.Length < 10)
            {
                yield return new ValidationResult("Invalid value for Text, length must be greater than 10.", new [] { "Text" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateComplaintRequest" />
    /// </summary>
    public class CreateComplaintRequestJsonConverter : JsonConverter<CreateComplaintRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateComplaintRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateComplaintRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<CreateComplaintRequest.CategoryEnum?> category = default;
            Option<string?> text = default;
            Option<Guid?> investorId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "category":
                            string? categoryRawValue = utf8JsonReader.GetString();
                            if (categoryRawValue != null)
                                category = new Option<CreateComplaintRequest.CategoryEnum?>(CreateComplaintRequest.CategoryEnumFromStringOrDefault(categoryRawValue));
                            break;
                        case "text":
                            text = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "investorId":
                            investorId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!category.IsSet)
                throw new ArgumentException("Property is required for class CreateComplaintRequest.", nameof(category));

            if (!text.IsSet)
                throw new ArgumentException("Property is required for class CreateComplaintRequest.", nameof(text));

            if (category.IsSet && category.Value == null)
                throw new ArgumentNullException(nameof(category), "Property is not nullable for class CreateComplaintRequest.");

            if (text.IsSet && text.Value == null)
                throw new ArgumentNullException(nameof(text), "Property is not nullable for class CreateComplaintRequest.");

            if (investorId.IsSet && investorId.Value == null)
                throw new ArgumentNullException(nameof(investorId), "Property is not nullable for class CreateComplaintRequest.");

            return new CreateComplaintRequest(category.Value!.Value!, text.Value!, investorId);
        }

        /// <summary>
        /// Serializes a <see cref="CreateComplaintRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createComplaintRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateComplaintRequest createComplaintRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createComplaintRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateComplaintRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createComplaintRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateComplaintRequest createComplaintRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createComplaintRequest.Text == null)
                throw new ArgumentNullException(nameof(createComplaintRequest.Text), "Property is required for class CreateComplaintRequest.");

            var categoryRawValue = CreateComplaintRequest.CategoryEnumToJsonValue(createComplaintRequest.Category);
            writer.WriteString("category", categoryRawValue);
            writer.WriteString("text", createComplaintRequest.Text);

            if (createComplaintRequest.InvestorIdOption.IsSet)
                writer.WriteString("investorId", createComplaintRequest.InvestorIdOption.Value!.Value);
        }
    }
}
