// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// FeedItem
    /// </summary>
    public partial class FeedItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FeedItem" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="type">type</param>
        /// <param name="timestamp">timestamp</param>
        /// <param name="title">Event title</param>
        /// <param name="description">Event description</param>
        /// <param name="clientId">clientId</param>
        /// <param name="clientName">clientName</param>
        /// <param name="issuanceId">issuanceId</param>
        /// <param name="amount">amount</param>
        /// <param name="status">status</param>
        /// <param name="metadata">Additional event data</param>
        [JsonConstructor]
        public FeedItem(Guid id, TypeEnum type, DateTime timestamp, Option<string?> title = default, Option<string?> description = default, Option<Guid?> clientId = default, Option<string?> clientName = default, Option<Guid?> issuanceId = default, Option<decimal?> amount = default, Option<StatusEnum?> status = default, Option<Dictionary<string, Object>?> metadata = default)
        {
            Id = id;
            Type = type;
            Timestamp = timestamp;
            TitleOption = title;
            DescriptionOption = description;
            ClientIdOption = clientId;
            ClientNameOption = clientName;
            IssuanceIdOption = issuanceId;
            AmountOption = amount;
            StatusOption = status;
            MetadataOption = metadata;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Order for value: order
            /// </summary>
            Order = 1,

            /// <summary>
            /// Enum Transfer for value: transfer
            /// </summary>
            Transfer = 2,

            /// <summary>
            /// Enum Payout for value: payout
            /// </summary>
            Payout = 3,

            /// <summary>
            /// Enum Kyc for value: kyc
            /// </summary>
            Kyc = 4,

            /// <summary>
            /// Enum Qualification for value: qualification
            /// </summary>
            Qualification = 5
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("order"))
                return TypeEnum.Order;

            if (value.Equals("transfer"))
                return TypeEnum.Transfer;

            if (value.Equals("payout"))
                return TypeEnum.Payout;

            if (value.Equals("kyc"))
                return TypeEnum.Kyc;

            if (value.Equals("qualification"))
                return TypeEnum.Qualification;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("order"))
                return TypeEnum.Order;

            if (value.Equals("transfer"))
                return TypeEnum.Transfer;

            if (value.Equals("payout"))
                return TypeEnum.Payout;

            if (value.Equals("kyc"))
                return TypeEnum.Kyc;

            if (value.Equals("qualification"))
                return TypeEnum.Qualification;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.Order)
                return "order";

            if (value == TypeEnum.Transfer)
                return "transfer";

            if (value == TypeEnum.Payout)
                return "payout";

            if (value == TypeEnum.Kyc)
                return "kyc";

            if (value == TypeEnum.Qualification)
                return "qualification";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            Pending = 1,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            Completed = 2,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("completed"))
                return StatusEnum.Completed;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("completed"))
                return StatusEnum.Completed;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.Pending)
                return "pending";

            if (value == StatusEnum.Completed)
                return "completed";

            if (value == StatusEnum.Failed)
                return "failed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Event title
        /// </summary>
        /// <value>Event title</value>
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Event description
        /// </summary>
        /// <value>Event description</value>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClientId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> ClientIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ClientId
        /// </summary>
        [JsonPropertyName("clientId")]
        public Guid? ClientId { get { return this.ClientIdOption; } set { this.ClientIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClientName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ClientNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ClientName
        /// </summary>
        [JsonPropertyName("clientName")]
        public string? ClientName { get { return this.ClientNameOption; } set { this.ClientNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of IssuanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IssuanceIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets IssuanceId
        /// </summary>
        [JsonPropertyName("issuanceId")]
        public Guid? IssuanceId { get { return this.IssuanceIdOption; } set { this.IssuanceIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public decimal? Amount { get { return this.AmountOption; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Metadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>?> MetadataOption { get; private set; }

        /// <summary>
        /// Additional event data
        /// </summary>
        /// <value>Additional event data</value>
        [JsonPropertyName("metadata")]
        public Dictionary<string, Object>? Metadata { get { return this.MetadataOption; } set { this.MetadataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FeedItem {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  ClientName: ").Append(ClientName).Append("\n");
            sb.Append("  IssuanceId: ").Append(IssuanceId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FeedItem" />
    /// </summary>
    public class FeedItemJsonConverter : JsonConverter<FeedItem>
    {
        /// <summary>
        /// The format to use to serialize Timestamp
        /// </summary>
        public static string TimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="FeedItem" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FeedItem Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<FeedItem.TypeEnum?> type = default;
            Option<DateTime?> timestamp = default;
            Option<string?> title = default;
            Option<string?> description = default;
            Option<Guid?> clientId = default;
            Option<string?> clientName = default;
            Option<Guid?> issuanceId = default;
            Option<decimal?> amount = default;
            Option<FeedItem.StatusEnum?> status = default;
            Option<Dictionary<string, Object>?> metadata = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<FeedItem.TypeEnum?>(FeedItem.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "timestamp":
                            timestamp = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "clientId":
                            clientId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "clientName":
                            clientName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "issuanceId":
                            issuanceId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "amount":
                            amount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<FeedItem.StatusEnum?>(FeedItem.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "metadata":
                            metadata = new Option<Dictionary<string, Object>?>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class FeedItem.", nameof(id));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class FeedItem.", nameof(type));

            if (!timestamp.IsSet)
                throw new ArgumentException("Property is required for class FeedItem.", nameof(timestamp));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class FeedItem.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class FeedItem.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class FeedItem.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class FeedItem.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class FeedItem.");

            if (clientId.IsSet && clientId.Value == null)
                throw new ArgumentNullException(nameof(clientId), "Property is not nullable for class FeedItem.");

            if (clientName.IsSet && clientName.Value == null)
                throw new ArgumentNullException(nameof(clientName), "Property is not nullable for class FeedItem.");

            if (issuanceId.IsSet && issuanceId.Value == null)
                throw new ArgumentNullException(nameof(issuanceId), "Property is not nullable for class FeedItem.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class FeedItem.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class FeedItem.");

            if (metadata.IsSet && metadata.Value == null)
                throw new ArgumentNullException(nameof(metadata), "Property is not nullable for class FeedItem.");

            return new FeedItem(id.Value!.Value!, type.Value!.Value!, timestamp.Value!.Value!, title, description, clientId, clientName, issuanceId, amount, status, metadata);
        }

        /// <summary>
        /// Serializes a <see cref="FeedItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="feedItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FeedItem feedItem, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, feedItem, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FeedItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="feedItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FeedItem feedItem, JsonSerializerOptions jsonSerializerOptions)
        {
            if (feedItem.TitleOption.IsSet && feedItem.Title == null)
                throw new ArgumentNullException(nameof(feedItem.Title), "Property is required for class FeedItem.");

            if (feedItem.DescriptionOption.IsSet && feedItem.Description == null)
                throw new ArgumentNullException(nameof(feedItem.Description), "Property is required for class FeedItem.");

            if (feedItem.ClientNameOption.IsSet && feedItem.ClientName == null)
                throw new ArgumentNullException(nameof(feedItem.ClientName), "Property is required for class FeedItem.");

            if (feedItem.MetadataOption.IsSet && feedItem.Metadata == null)
                throw new ArgumentNullException(nameof(feedItem.Metadata), "Property is required for class FeedItem.");

            writer.WriteString("id", feedItem.Id);

            var typeRawValue = FeedItem.TypeEnumToJsonValue(feedItem.Type);
            writer.WriteString("type", typeRawValue);
            writer.WriteString("timestamp", feedItem.Timestamp.ToString(TimestampFormat));

            if (feedItem.TitleOption.IsSet)
                writer.WriteString("title", feedItem.Title);

            if (feedItem.DescriptionOption.IsSet)
                writer.WriteString("description", feedItem.Description);

            if (feedItem.ClientIdOption.IsSet)
                writer.WriteString("clientId", feedItem.ClientIdOption.Value!.Value);

            if (feedItem.ClientNameOption.IsSet)
                writer.WriteString("clientName", feedItem.ClientName);

            if (feedItem.IssuanceIdOption.IsSet)
                writer.WriteString("issuanceId", feedItem.IssuanceIdOption.Value!.Value);

            if (feedItem.AmountOption.IsSet)
                writer.WriteNumber("amount", feedItem.AmountOption.Value!.Value);

            var statusRawValue = FeedItem.StatusEnumToJsonValue(feedItem.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
            if (feedItem.MetadataOption.IsSet)
            {
                writer.WritePropertyName("metadata");
                JsonSerializer.Serialize(writer, feedItem.Metadata, jsonSerializerOptions);
            }
        }
    }
}
