// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Holding
    /// </summary>
    public partial class Holding : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Holding" /> class.
        /// </summary>
        /// <param name="assetId">assetId</param>
        /// <param name="assetCode">assetCode</param>
        /// <param name="assetName">assetName</param>
        /// <param name="amount">amount</param>
        [JsonConstructor]
        public Holding(Option<Guid?> assetId = default, Option<string?> assetCode = default, Option<string?> assetName = default, Option<decimal?> amount = default)
        {
            AssetIdOption = assetId;
            AssetCodeOption = assetCode;
            AssetNameOption = assetName;
            AmountOption = amount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AssetId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> AssetIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [JsonPropertyName("assetId")]
        public Guid? AssetId { get { return this.AssetIdOption; } set { this.AssetIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssetCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AssetCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssetCode
        /// </summary>
        [JsonPropertyName("assetCode")]
        public string? AssetCode { get { return this.AssetCodeOption; } set { this.AssetCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssetName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AssetNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssetName
        /// </summary>
        [JsonPropertyName("assetName")]
        public string? AssetName { get { return this.AssetNameOption; } set { this.AssetNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public decimal? Amount { get { return this.AmountOption; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Holding {\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  AssetCode: ").Append(AssetCode).Append("\n");
            sb.Append("  AssetName: ").Append(AssetName).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Holding" />
    /// </summary>
    public class HoldingJsonConverter : JsonConverter<Holding>
    {
        /// <summary>
        /// Deserializes json to <see cref="Holding" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Holding Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> assetId = default;
            Option<string?> assetCode = default;
            Option<string?> assetName = default;
            Option<decimal?> amount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "assetId":
                            assetId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "assetCode":
                            assetCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "assetName":
                            assetName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "amount":
                            amount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (assetId.IsSet && assetId.Value == null)
                throw new ArgumentNullException(nameof(assetId), "Property is not nullable for class Holding.");

            if (assetCode.IsSet && assetCode.Value == null)
                throw new ArgumentNullException(nameof(assetCode), "Property is not nullable for class Holding.");

            if (assetName.IsSet && assetName.Value == null)
                throw new ArgumentNullException(nameof(assetName), "Property is not nullable for class Holding.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class Holding.");

            return new Holding(assetId, assetCode, assetName, amount);
        }

        /// <summary>
        /// Serializes a <see cref="Holding" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="holding"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Holding holding, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, holding, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Holding" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="holding"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Holding holding, JsonSerializerOptions jsonSerializerOptions)
        {
            if (holding.AssetCodeOption.IsSet && holding.AssetCode == null)
                throw new ArgumentNullException(nameof(holding.AssetCode), "Property is required for class Holding.");

            if (holding.AssetNameOption.IsSet && holding.AssetName == null)
                throw new ArgumentNullException(nameof(holding.AssetName), "Property is required for class Holding.");

            if (holding.AssetIdOption.IsSet)
                writer.WriteString("assetId", holding.AssetIdOption.Value!.Value);

            if (holding.AssetCodeOption.IsSet)
                writer.WriteString("assetCode", holding.AssetCode);

            if (holding.AssetNameOption.IsSet)
                writer.WriteString("assetName", holding.AssetName);

            if (holding.AmountOption.IsSet)
                writer.WriteNumber("amount", holding.AmountOption.Value!.Value);
        }
    }
}
