// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InvestorStatusResponse
    /// </summary>
    public partial class InvestorStatusResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InvestorStatusResponse" /> class.
        /// </summary>
        /// <param name="investorId">investorId</param>
        /// <param name="kyc">kyc</param>
        /// <param name="qualificationTier">qualificationTier</param>
        /// <param name="qualificationLimit">qualificationLimit</param>
        /// <param name="qualificationUsed">qualificationUsed</param>
        /// <param name="updatedAt">updatedAt</param>
        [JsonConstructor]
        public InvestorStatusResponse(Guid investorId, KycEnum kyc, QualificationTierEnum qualificationTier, Option<decimal?> qualificationLimit = default, Option<decimal?> qualificationUsed = default, Option<DateTime?> updatedAt = default)
        {
            InvestorId = investorId;
            Kyc = kyc;
            QualificationTier = qualificationTier;
            QualificationLimitOption = qualificationLimit;
            QualificationUsedOption = qualificationUsed;
            UpdatedAtOption = updatedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Kyc
        /// </summary>
        public enum KycEnum
        {
            /// <summary>
            /// Enum Pass for value: pass
            /// </summary>
            Pass = 1,

            /// <summary>
            /// Enum Fail for value: fail
            /// </summary>
            Fail = 2,

            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            Pending = 3,

            /// <summary>
            /// Enum Review for value: review
            /// </summary>
            Review = 4
        }

        /// <summary>
        /// Returns a <see cref="KycEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static KycEnum KycEnumFromString(string value)
        {
            if (value.Equals("pass"))
                return KycEnum.Pass;

            if (value.Equals("fail"))
                return KycEnum.Fail;

            if (value.Equals("pending"))
                return KycEnum.Pending;

            if (value.Equals("review"))
                return KycEnum.Review;

            throw new NotImplementedException($"Could not convert value to type KycEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="KycEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static KycEnum? KycEnumFromStringOrDefault(string value)
        {
            if (value.Equals("pass"))
                return KycEnum.Pass;

            if (value.Equals("fail"))
                return KycEnum.Fail;

            if (value.Equals("pending"))
                return KycEnum.Pending;

            if (value.Equals("review"))
                return KycEnum.Review;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="KycEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string KycEnumToJsonValue(KycEnum value)
        {
            if (value == KycEnum.Pass)
                return "pass";

            if (value == KycEnum.Fail)
                return "fail";

            if (value == KycEnum.Pending)
                return "pending";

            if (value == KycEnum.Review)
                return "review";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Kyc
        /// </summary>
        [JsonPropertyName("kyc")]
        public KycEnum Kyc { get; set; }

        /// <summary>
        /// Defines QualificationTier
        /// </summary>
        public enum QualificationTierEnum
        {
            /// <summary>
            /// Enum Unqualified for value: unqualified
            /// </summary>
            Unqualified = 1,

            /// <summary>
            /// Enum Qualified for value: qualified
            /// </summary>
            Qualified = 2,

            /// <summary>
            /// Enum Professional for value: professional
            /// </summary>
            Professional = 3
        }

        /// <summary>
        /// Returns a <see cref="QualificationTierEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static QualificationTierEnum QualificationTierEnumFromString(string value)
        {
            if (value.Equals("unqualified"))
                return QualificationTierEnum.Unqualified;

            if (value.Equals("qualified"))
                return QualificationTierEnum.Qualified;

            if (value.Equals("professional"))
                return QualificationTierEnum.Professional;

            throw new NotImplementedException($"Could not convert value to type QualificationTierEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="QualificationTierEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static QualificationTierEnum? QualificationTierEnumFromStringOrDefault(string value)
        {
            if (value.Equals("unqualified"))
                return QualificationTierEnum.Unqualified;

            if (value.Equals("qualified"))
                return QualificationTierEnum.Qualified;

            if (value.Equals("professional"))
                return QualificationTierEnum.Professional;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="QualificationTierEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string QualificationTierEnumToJsonValue(QualificationTierEnum value)
        {
            if (value == QualificationTierEnum.Unqualified)
                return "unqualified";

            if (value == QualificationTierEnum.Qualified)
                return "qualified";

            if (value == QualificationTierEnum.Professional)
                return "professional";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets QualificationTier
        /// </summary>
        [JsonPropertyName("qualificationTier")]
        public QualificationTierEnum QualificationTier { get; set; }

        /// <summary>
        /// Gets or Sets InvestorId
        /// </summary>
        [JsonPropertyName("investorId")]
        public Guid InvestorId { get; set; }

        /// <summary>
        /// Used to track the state of QualificationLimit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> QualificationLimitOption { get; private set; }

        /// <summary>
        /// Gets or Sets QualificationLimit
        /// </summary>
        [JsonPropertyName("qualificationLimit")]
        public decimal? QualificationLimit { get { return this.QualificationLimitOption; } set { this.QualificationLimitOption = new(value); } }

        /// <summary>
        /// Used to track the state of QualificationUsed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> QualificationUsedOption { get; private set; }

        /// <summary>
        /// Gets or Sets QualificationUsed
        /// </summary>
        [JsonPropertyName("qualificationUsed")]
        public decimal? QualificationUsed { get { return this.QualificationUsedOption; } set { this.QualificationUsedOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> UpdatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTime? UpdatedAt { get { return this.UpdatedAtOption; } set { this.UpdatedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InvestorStatusResponse {\n");
            sb.Append("  InvestorId: ").Append(InvestorId).Append("\n");
            sb.Append("  Kyc: ").Append(Kyc).Append("\n");
            sb.Append("  QualificationTier: ").Append(QualificationTier).Append("\n");
            sb.Append("  QualificationLimit: ").Append(QualificationLimit).Append("\n");
            sb.Append("  QualificationUsed: ").Append(QualificationUsed).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InvestorStatusResponse" />
    /// </summary>
    public class InvestorStatusResponseJsonConverter : JsonConverter<InvestorStatusResponse>
    {
        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="InvestorStatusResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InvestorStatusResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> investorId = default;
            Option<InvestorStatusResponse.KycEnum?> kyc = default;
            Option<InvestorStatusResponse.QualificationTierEnum?> qualificationTier = default;
            Option<decimal?> qualificationLimit = default;
            Option<decimal?> qualificationUsed = default;
            Option<DateTime?> updatedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "investorId":
                            investorId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "kyc":
                            string? kycRawValue = utf8JsonReader.GetString();
                            if (kycRawValue != null)
                                kyc = new Option<InvestorStatusResponse.KycEnum?>(InvestorStatusResponse.KycEnumFromStringOrDefault(kycRawValue));
                            break;
                        case "qualificationTier":
                            string? qualificationTierRawValue = utf8JsonReader.GetString();
                            if (qualificationTierRawValue != null)
                                qualificationTier = new Option<InvestorStatusResponse.QualificationTierEnum?>(InvestorStatusResponse.QualificationTierEnumFromStringOrDefault(qualificationTierRawValue));
                            break;
                        case "qualificationLimit":
                            qualificationLimit = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "qualificationUsed":
                            qualificationUsed = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!investorId.IsSet)
                throw new ArgumentException("Property is required for class InvestorStatusResponse.", nameof(investorId));

            if (!kyc.IsSet)
                throw new ArgumentException("Property is required for class InvestorStatusResponse.", nameof(kyc));

            if (!qualificationTier.IsSet)
                throw new ArgumentException("Property is required for class InvestorStatusResponse.", nameof(qualificationTier));

            if (investorId.IsSet && investorId.Value == null)
                throw new ArgumentNullException(nameof(investorId), "Property is not nullable for class InvestorStatusResponse.");

            if (kyc.IsSet && kyc.Value == null)
                throw new ArgumentNullException(nameof(kyc), "Property is not nullable for class InvestorStatusResponse.");

            if (qualificationTier.IsSet && qualificationTier.Value == null)
                throw new ArgumentNullException(nameof(qualificationTier), "Property is not nullable for class InvestorStatusResponse.");

            if (qualificationLimit.IsSet && qualificationLimit.Value == null)
                throw new ArgumentNullException(nameof(qualificationLimit), "Property is not nullable for class InvestorStatusResponse.");

            if (qualificationUsed.IsSet && qualificationUsed.Value == null)
                throw new ArgumentNullException(nameof(qualificationUsed), "Property is not nullable for class InvestorStatusResponse.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class InvestorStatusResponse.");

            return new InvestorStatusResponse(investorId.Value!.Value!, kyc.Value!.Value!, qualificationTier.Value!.Value!, qualificationLimit, qualificationUsed, updatedAt);
        }

        /// <summary>
        /// Serializes a <see cref="InvestorStatusResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="investorStatusResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InvestorStatusResponse investorStatusResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, investorStatusResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InvestorStatusResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="investorStatusResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InvestorStatusResponse investorStatusResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("investorId", investorStatusResponse.InvestorId);

            var kycRawValue = InvestorStatusResponse.KycEnumToJsonValue(investorStatusResponse.Kyc);
            writer.WriteString("kyc", kycRawValue);
            var qualificationTierRawValue = InvestorStatusResponse.QualificationTierEnumToJsonValue(investorStatusResponse.QualificationTier);
            writer.WriteString("qualificationTier", qualificationTierRawValue);
            if (investorStatusResponse.QualificationLimitOption.IsSet)
                writer.WriteNumber("qualificationLimit", investorStatusResponse.QualificationLimitOption.Value!.Value);

            if (investorStatusResponse.QualificationUsedOption.IsSet)
                writer.WriteNumber("qualificationUsed", investorStatusResponse.QualificationUsedOption.Value!.Value);

            if (investorStatusResponse.UpdatedAtOption.IsSet)
                writer.WriteString("updatedAt", investorStatusResponse.UpdatedAtOption.Value!.Value.ToString(UpdatedAtFormat));
        }
    }
}
