// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// IssuerIssuancesReportResponse
    /// </summary>
    public partial class IssuerIssuancesReportResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IssuerIssuancesReportResponse" /> class.
        /// </summary>
        /// <param name="issuerId">issuerId</param>
        /// <param name="period">period</param>
        /// <param name="items">items</param>
        /// <param name="summary">summary</param>
        [JsonConstructor]
        public IssuerIssuancesReportResponse(Option<Guid?> issuerId = default, Option<PayoutsReportResponsePeriod?> period = default, Option<List<IssuerReportRow>?> items = default, Option<IssuerIssuancesReportResponseSummary?> summary = default)
        {
            IssuerIdOption = issuerId;
            PeriodOption = period;
            ItemsOption = items;
            SummaryOption = summary;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of IssuerId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IssuerIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets IssuerId
        /// </summary>
        [JsonPropertyName("issuerId")]
        public Guid? IssuerId { get { return this.IssuerIdOption; } set { this.IssuerIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Period
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PayoutsReportResponsePeriod?> PeriodOption { get; private set; }

        /// <summary>
        /// Gets or Sets Period
        /// </summary>
        [JsonPropertyName("period")]
        public PayoutsReportResponsePeriod? Period { get { return this.PeriodOption; } set { this.PeriodOption = new(value); } }

        /// <summary>
        /// Used to track the state of Items
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<IssuerReportRow>?> ItemsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [JsonPropertyName("items")]
        public List<IssuerReportRow>? Items { get { return this.ItemsOption; } set { this.ItemsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Summary
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<IssuerIssuancesReportResponseSummary?> SummaryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Summary
        /// </summary>
        [JsonPropertyName("summary")]
        public IssuerIssuancesReportResponseSummary? Summary { get { return this.SummaryOption; } set { this.SummaryOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IssuerIssuancesReportResponse {\n");
            sb.Append("  IssuerId: ").Append(IssuerId).Append("\n");
            sb.Append("  Period: ").Append(Period).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  Summary: ").Append(Summary).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IssuerIssuancesReportResponse" />
    /// </summary>
    public class IssuerIssuancesReportResponseJsonConverter : JsonConverter<IssuerIssuancesReportResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="IssuerIssuancesReportResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override IssuerIssuancesReportResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> issuerId = default;
            Option<PayoutsReportResponsePeriod?> period = default;
            Option<List<IssuerReportRow>?> items = default;
            Option<IssuerIssuancesReportResponseSummary?> summary = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "issuerId":
                            issuerId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "period":
                            period = new Option<PayoutsReportResponsePeriod?>(JsonSerializer.Deserialize<PayoutsReportResponsePeriod>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "items":
                            items = new Option<List<IssuerReportRow>?>(JsonSerializer.Deserialize<List<IssuerReportRow>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "summary":
                            summary = new Option<IssuerIssuancesReportResponseSummary?>(JsonSerializer.Deserialize<IssuerIssuancesReportResponseSummary>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (issuerId.IsSet && issuerId.Value == null)
                throw new ArgumentNullException(nameof(issuerId), "Property is not nullable for class IssuerIssuancesReportResponse.");

            if (period.IsSet && period.Value == null)
                throw new ArgumentNullException(nameof(period), "Property is not nullable for class IssuerIssuancesReportResponse.");

            if (items.IsSet && items.Value == null)
                throw new ArgumentNullException(nameof(items), "Property is not nullable for class IssuerIssuancesReportResponse.");

            if (summary.IsSet && summary.Value == null)
                throw new ArgumentNullException(nameof(summary), "Property is not nullable for class IssuerIssuancesReportResponse.");

            return new IssuerIssuancesReportResponse(issuerId, period, items, summary);
        }

        /// <summary>
        /// Serializes a <see cref="IssuerIssuancesReportResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issuerIssuancesReportResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, IssuerIssuancesReportResponse issuerIssuancesReportResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, issuerIssuancesReportResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="IssuerIssuancesReportResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issuerIssuancesReportResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, IssuerIssuancesReportResponse issuerIssuancesReportResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (issuerIssuancesReportResponse.PeriodOption.IsSet && issuerIssuancesReportResponse.Period == null)
                throw new ArgumentNullException(nameof(issuerIssuancesReportResponse.Period), "Property is required for class IssuerIssuancesReportResponse.");

            if (issuerIssuancesReportResponse.ItemsOption.IsSet && issuerIssuancesReportResponse.Items == null)
                throw new ArgumentNullException(nameof(issuerIssuancesReportResponse.Items), "Property is required for class IssuerIssuancesReportResponse.");

            if (issuerIssuancesReportResponse.SummaryOption.IsSet && issuerIssuancesReportResponse.Summary == null)
                throw new ArgumentNullException(nameof(issuerIssuancesReportResponse.Summary), "Property is required for class IssuerIssuancesReportResponse.");

            if (issuerIssuancesReportResponse.IssuerIdOption.IsSet)
                writer.WriteString("issuerId", issuerIssuancesReportResponse.IssuerIdOption.Value!.Value);

            if (issuerIssuancesReportResponse.PeriodOption.IsSet)
            {
                writer.WritePropertyName("period");
                JsonSerializer.Serialize(writer, issuerIssuancesReportResponse.Period, jsonSerializerOptions);
            }
            if (issuerIssuancesReportResponse.ItemsOption.IsSet)
            {
                writer.WritePropertyName("items");
                JsonSerializer.Serialize(writer, issuerIssuancesReportResponse.Items, jsonSerializerOptions);
            }
            if (issuerIssuancesReportResponse.SummaryOption.IsSet)
            {
                writer.WritePropertyName("summary");
                JsonSerializer.Serialize(writer, issuerIssuancesReportResponse.Summary, jsonSerializerOptions);
            }
        }
    }
}
