// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// IssuerReportRow
    /// </summary>
    public partial class IssuerReportRow : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IssuerReportRow" /> class.
        /// </summary>
        /// <param name="issuanceId">issuanceId</param>
        /// <param name="assetCode">assetCode</param>
        /// <param name="assetName">assetName</param>
        /// <param name="totalAmount">totalAmount</param>
        /// <param name="soldAmount">soldAmount</param>
        /// <param name="investorsCount">investorsCount</param>
        /// <param name="status">status</param>
        /// <param name="issueDate">issueDate</param>
        /// <param name="maturityDate">maturityDate</param>
        /// <param name="publishedAt">publishedAt</param>
        [JsonConstructor]
        public IssuerReportRow(Option<Guid?> issuanceId = default, Option<string?> assetCode = default, Option<string?> assetName = default, Option<decimal?> totalAmount = default, Option<decimal?> soldAmount = default, Option<int?> investorsCount = default, Option<StatusEnum?> status = default, Option<DateOnly?> issueDate = default, Option<DateOnly?> maturityDate = default, Option<DateTime?> publishedAt = default)
        {
            IssuanceIdOption = issuanceId;
            AssetCodeOption = assetCode;
            AssetNameOption = assetName;
            TotalAmountOption = totalAmount;
            SoldAmountOption = soldAmount;
            InvestorsCountOption = investorsCount;
            StatusOption = status;
            IssueDateOption = issueDate;
            MaturityDateOption = maturityDate;
            PublishedAtOption = publishedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Draft for value: draft
            /// </summary>
            Draft = 1,

            /// <summary>
            /// Enum Published for value: published
            /// </summary>
            Published = 2,

            /// <summary>
            /// Enum Closed for value: closed
            /// </summary>
            Closed = 3,

            /// <summary>
            /// Enum Redeemed for value: redeemed
            /// </summary>
            Redeemed = 4
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("draft"))
                return StatusEnum.Draft;

            if (value.Equals("published"))
                return StatusEnum.Published;

            if (value.Equals("closed"))
                return StatusEnum.Closed;

            if (value.Equals("redeemed"))
                return StatusEnum.Redeemed;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("draft"))
                return StatusEnum.Draft;

            if (value.Equals("published"))
                return StatusEnum.Published;

            if (value.Equals("closed"))
                return StatusEnum.Closed;

            if (value.Equals("redeemed"))
                return StatusEnum.Redeemed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.Draft)
                return "draft";

            if (value == StatusEnum.Published)
                return "published";

            if (value == StatusEnum.Closed)
                return "closed";

            if (value == StatusEnum.Redeemed)
                return "redeemed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of IssuanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IssuanceIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets IssuanceId
        /// </summary>
        [JsonPropertyName("issuanceId")]
        public Guid? IssuanceId { get { return this.IssuanceIdOption; } set { this.IssuanceIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssetCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AssetCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssetCode
        /// </summary>
        [JsonPropertyName("assetCode")]
        public string? AssetCode { get { return this.AssetCodeOption; } set { this.AssetCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssetName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AssetNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssetName
        /// </summary>
        [JsonPropertyName("assetName")]
        public string? AssetName { get { return this.AssetNameOption; } set { this.AssetNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> TotalAmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalAmount
        /// </summary>
        [JsonPropertyName("totalAmount")]
        public decimal? TotalAmount { get { return this.TotalAmountOption; } set { this.TotalAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of SoldAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> SoldAmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets SoldAmount
        /// </summary>
        [JsonPropertyName("soldAmount")]
        public decimal? SoldAmount { get { return this.SoldAmountOption; } set { this.SoldAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of InvestorsCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> InvestorsCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets InvestorsCount
        /// </summary>
        [JsonPropertyName("investorsCount")]
        public int? InvestorsCount { get { return this.InvestorsCountOption; } set { this.InvestorsCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of IssueDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> IssueDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets IssueDate
        /// </summary>
        [JsonPropertyName("issueDate")]
        public DateOnly? IssueDate { get { return this.IssueDateOption; } set { this.IssueDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of MaturityDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> MaturityDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets MaturityDate
        /// </summary>
        [JsonPropertyName("maturityDate")]
        public DateOnly? MaturityDate { get { return this.MaturityDateOption; } set { this.MaturityDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of PublishedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> PublishedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets PublishedAt
        /// </summary>
        [JsonPropertyName("publishedAt")]
        public DateTime? PublishedAt { get { return this.PublishedAtOption; } set { this.PublishedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IssuerReportRow {\n");
            sb.Append("  IssuanceId: ").Append(IssuanceId).Append("\n");
            sb.Append("  AssetCode: ").Append(AssetCode).Append("\n");
            sb.Append("  AssetName: ").Append(AssetName).Append("\n");
            sb.Append("  TotalAmount: ").Append(TotalAmount).Append("\n");
            sb.Append("  SoldAmount: ").Append(SoldAmount).Append("\n");
            sb.Append("  InvestorsCount: ").Append(InvestorsCount).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  IssueDate: ").Append(IssueDate).Append("\n");
            sb.Append("  MaturityDate: ").Append(MaturityDate).Append("\n");
            sb.Append("  PublishedAt: ").Append(PublishedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IssuerReportRow" />
    /// </summary>
    public class IssuerReportRowJsonConverter : JsonConverter<IssuerReportRow>
    {
        /// <summary>
        /// The format to use to serialize IssueDate
        /// </summary>
        public static string IssueDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize MaturityDate
        /// </summary>
        public static string MaturityDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize PublishedAt
        /// </summary>
        public static string PublishedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="IssuerReportRow" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override IssuerReportRow Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> issuanceId = default;
            Option<string?> assetCode = default;
            Option<string?> assetName = default;
            Option<decimal?> totalAmount = default;
            Option<decimal?> soldAmount = default;
            Option<int?> investorsCount = default;
            Option<IssuerReportRow.StatusEnum?> status = default;
            Option<DateOnly?> issueDate = default;
            Option<DateOnly?> maturityDate = default;
            Option<DateTime?> publishedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "issuanceId":
                            issuanceId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "assetCode":
                            assetCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "assetName":
                            assetName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "totalAmount":
                            totalAmount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "soldAmount":
                            soldAmount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "investorsCount":
                            investorsCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<IssuerReportRow.StatusEnum?>(IssuerReportRow.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "issueDate":
                            issueDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "maturityDate":
                            maturityDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "publishedAt":
                            publishedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (issuanceId.IsSet && issuanceId.Value == null)
                throw new ArgumentNullException(nameof(issuanceId), "Property is not nullable for class IssuerReportRow.");

            if (assetCode.IsSet && assetCode.Value == null)
                throw new ArgumentNullException(nameof(assetCode), "Property is not nullable for class IssuerReportRow.");

            if (assetName.IsSet && assetName.Value == null)
                throw new ArgumentNullException(nameof(assetName), "Property is not nullable for class IssuerReportRow.");

            if (totalAmount.IsSet && totalAmount.Value == null)
                throw new ArgumentNullException(nameof(totalAmount), "Property is not nullable for class IssuerReportRow.");

            if (soldAmount.IsSet && soldAmount.Value == null)
                throw new ArgumentNullException(nameof(soldAmount), "Property is not nullable for class IssuerReportRow.");

            if (investorsCount.IsSet && investorsCount.Value == null)
                throw new ArgumentNullException(nameof(investorsCount), "Property is not nullable for class IssuerReportRow.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class IssuerReportRow.");

            if (issueDate.IsSet && issueDate.Value == null)
                throw new ArgumentNullException(nameof(issueDate), "Property is not nullable for class IssuerReportRow.");

            if (maturityDate.IsSet && maturityDate.Value == null)
                throw new ArgumentNullException(nameof(maturityDate), "Property is not nullable for class IssuerReportRow.");

            if (publishedAt.IsSet && publishedAt.Value == null)
                throw new ArgumentNullException(nameof(publishedAt), "Property is not nullable for class IssuerReportRow.");

            return new IssuerReportRow(issuanceId, assetCode, assetName, totalAmount, soldAmount, investorsCount, status, issueDate, maturityDate, publishedAt);
        }

        /// <summary>
        /// Serializes a <see cref="IssuerReportRow" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issuerReportRow"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, IssuerReportRow issuerReportRow, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, issuerReportRow, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="IssuerReportRow" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="issuerReportRow"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, IssuerReportRow issuerReportRow, JsonSerializerOptions jsonSerializerOptions)
        {
            if (issuerReportRow.AssetCodeOption.IsSet && issuerReportRow.AssetCode == null)
                throw new ArgumentNullException(nameof(issuerReportRow.AssetCode), "Property is required for class IssuerReportRow.");

            if (issuerReportRow.AssetNameOption.IsSet && issuerReportRow.AssetName == null)
                throw new ArgumentNullException(nameof(issuerReportRow.AssetName), "Property is required for class IssuerReportRow.");

            if (issuerReportRow.IssuanceIdOption.IsSet)
                writer.WriteString("issuanceId", issuerReportRow.IssuanceIdOption.Value!.Value);

            if (issuerReportRow.AssetCodeOption.IsSet)
                writer.WriteString("assetCode", issuerReportRow.AssetCode);

            if (issuerReportRow.AssetNameOption.IsSet)
                writer.WriteString("assetName", issuerReportRow.AssetName);

            if (issuerReportRow.TotalAmountOption.IsSet)
                writer.WriteNumber("totalAmount", issuerReportRow.TotalAmountOption.Value!.Value);

            if (issuerReportRow.SoldAmountOption.IsSet)
                writer.WriteNumber("soldAmount", issuerReportRow.SoldAmountOption.Value!.Value);

            if (issuerReportRow.InvestorsCountOption.IsSet)
                writer.WriteNumber("investorsCount", issuerReportRow.InvestorsCountOption.Value!.Value);

            var statusRawValue = IssuerReportRow.StatusEnumToJsonValue(issuerReportRow.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
            if (issuerReportRow.IssueDateOption.IsSet)
                writer.WriteString("issueDate", issuerReportRow.IssueDateOption.Value!.Value.ToString(IssueDateFormat));

            if (issuerReportRow.MaturityDateOption.IsSet)
                writer.WriteString("maturityDate", issuerReportRow.MaturityDateOption.Value!.Value.ToString(MaturityDateFormat));

            if (issuerReportRow.PublishedAtOption.IsSet)
                writer.WriteString("publishedAt", issuerReportRow.PublishedAtOption.Value!.Value.ToString(PublishedAtFormat));
        }
    }
}
