// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// KycDecisionResponse
    /// </summary>
    public partial class KycDecisionResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KycDecisionResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="investorId">investorId</param>
        /// <param name="status">status</param>
        /// <param name="comment">comment</param>
        /// <param name="decisionBy">User who made the decision</param>
        /// <param name="decisionAt">decisionAt</param>
        [JsonConstructor]
        public KycDecisionResponse(Option<Guid?> id = default, Option<Guid?> investorId = default, Option<StatusEnum?> status = default, Option<string?> comment = default, Option<Guid?> decisionBy = default, Option<DateTime?> decisionAt = default)
        {
            IdOption = id;
            InvestorIdOption = investorId;
            StatusOption = status;
            CommentOption = comment;
            DecisionByOption = decisionBy;
            DecisionAtOption = decisionAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Approved for value: approved
            /// </summary>
            Approved = 1,

            /// <summary>
            /// Enum Rejected for value: rejected
            /// </summary>
            Rejected = 2
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("approved"))
                return StatusEnum.Approved;

            if (value.Equals("rejected"))
                return StatusEnum.Rejected;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("approved"))
                return StatusEnum.Approved;

            if (value.Equals("rejected"))
                return StatusEnum.Rejected;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.Approved)
                return "approved";

            if (value == StatusEnum.Rejected)
                return "rejected";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InvestorId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> InvestorIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets InvestorId
        /// </summary>
        [JsonPropertyName("investorId")]
        public Guid? InvestorId { get { return this.InvestorIdOption; } set { this.InvestorIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Comment
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CommentOption { get; private set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [JsonPropertyName("comment")]
        public string? Comment { get { return this.CommentOption; } set { this.CommentOption = new(value); } }

        /// <summary>
        /// Used to track the state of DecisionBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> DecisionByOption { get; private set; }

        /// <summary>
        /// User who made the decision
        /// </summary>
        /// <value>User who made the decision</value>
        [JsonPropertyName("decisionBy")]
        public Guid? DecisionBy { get { return this.DecisionByOption; } set { this.DecisionByOption = new(value); } }

        /// <summary>
        /// Used to track the state of DecisionAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> DecisionAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets DecisionAt
        /// </summary>
        [JsonPropertyName("decisionAt")]
        public DateTime? DecisionAt { get { return this.DecisionAtOption; } set { this.DecisionAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KycDecisionResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  InvestorId: ").Append(InvestorId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  DecisionBy: ").Append(DecisionBy).Append("\n");
            sb.Append("  DecisionAt: ").Append(DecisionAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="KycDecisionResponse" />
    /// </summary>
    public class KycDecisionResponseJsonConverter : JsonConverter<KycDecisionResponse>
    {
        /// <summary>
        /// The format to use to serialize DecisionAt
        /// </summary>
        public static string DecisionAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="KycDecisionResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override KycDecisionResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> investorId = default;
            Option<KycDecisionResponse.StatusEnum?> status = default;
            Option<string?> comment = default;
            Option<Guid?> decisionBy = default;
            Option<DateTime?> decisionAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "investorId":
                            investorId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<KycDecisionResponse.StatusEnum?>(KycDecisionResponse.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "comment":
                            comment = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "decisionBy":
                            decisionBy = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "decisionAt":
                            decisionAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class KycDecisionResponse.");

            if (investorId.IsSet && investorId.Value == null)
                throw new ArgumentNullException(nameof(investorId), "Property is not nullable for class KycDecisionResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class KycDecisionResponse.");

            if (comment.IsSet && comment.Value == null)
                throw new ArgumentNullException(nameof(comment), "Property is not nullable for class KycDecisionResponse.");

            if (decisionBy.IsSet && decisionBy.Value == null)
                throw new ArgumentNullException(nameof(decisionBy), "Property is not nullable for class KycDecisionResponse.");

            if (decisionAt.IsSet && decisionAt.Value == null)
                throw new ArgumentNullException(nameof(decisionAt), "Property is not nullable for class KycDecisionResponse.");

            return new KycDecisionResponse(id, investorId, status, comment, decisionBy, decisionAt);
        }

        /// <summary>
        /// Serializes a <see cref="KycDecisionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="kycDecisionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, KycDecisionResponse kycDecisionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, kycDecisionResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="KycDecisionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="kycDecisionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, KycDecisionResponse kycDecisionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (kycDecisionResponse.CommentOption.IsSet && kycDecisionResponse.Comment == null)
                throw new ArgumentNullException(nameof(kycDecisionResponse.Comment), "Property is required for class KycDecisionResponse.");

            if (kycDecisionResponse.IdOption.IsSet)
                writer.WriteString("id", kycDecisionResponse.IdOption.Value!.Value);

            if (kycDecisionResponse.InvestorIdOption.IsSet)
                writer.WriteString("investorId", kycDecisionResponse.InvestorIdOption.Value!.Value);

            var statusRawValue = KycDecisionResponse.StatusEnumToJsonValue(kycDecisionResponse.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
            if (kycDecisionResponse.CommentOption.IsSet)
                writer.WriteString("comment", kycDecisionResponse.Comment);

            if (kycDecisionResponse.DecisionByOption.IsSet)
                writer.WriteString("decisionBy", kycDecisionResponse.DecisionByOption.Value!.Value);

            if (kycDecisionResponse.DecisionAtOption.IsSet)
                writer.WriteString("decisionAt", kycDecisionResponse.DecisionAtOption.Value!.Value.ToString(DecisionAtFormat));
        }
    }
}
