// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// KycResult
    /// </summary>
    public partial class KycResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KycResult" /> class.
        /// </summary>
        /// <param name="investorId">investorId</param>
        /// <param name="status">status</param>
        /// <param name="checkedAt">checkedAt</param>
        /// <param name="reason">reason</param>
        [JsonConstructor]
        public KycResult(Guid investorId, StatusEnum status, Option<DateTime?> checkedAt = default, Option<string?> reason = default)
        {
            InvestorId = investorId;
            Status = status;
            CheckedAtOption = checkedAt;
            ReasonOption = reason;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pass for value: pass
            /// </summary>
            Pass = 1,

            /// <summary>
            /// Enum Fail for value: fail
            /// </summary>
            Fail = 2,

            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            Pending = 3,

            /// <summary>
            /// Enum Review for value: review
            /// </summary>
            Review = 4
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("pass"))
                return StatusEnum.Pass;

            if (value.Equals("fail"))
                return StatusEnum.Fail;

            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("review"))
                return StatusEnum.Review;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("pass"))
                return StatusEnum.Pass;

            if (value.Equals("fail"))
                return StatusEnum.Fail;

            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("review"))
                return StatusEnum.Review;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Pass)
                return "pass";

            if (value == StatusEnum.Fail)
                return "fail";

            if (value == StatusEnum.Pending)
                return "pending";

            if (value == StatusEnum.Review)
                return "review";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets InvestorId
        /// </summary>
        [JsonPropertyName("investorId")]
        public Guid InvestorId { get; set; }

        /// <summary>
        /// Used to track the state of CheckedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CheckedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CheckedAt
        /// </summary>
        [JsonPropertyName("checkedAt")]
        public DateTime? CheckedAt { get { return this.CheckedAtOption; } set { this.CheckedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of Reason
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReasonOption { get; private set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [JsonPropertyName("reason")]
        public string? Reason { get { return this.ReasonOption; } set { this.ReasonOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KycResult {\n");
            sb.Append("  InvestorId: ").Append(InvestorId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CheckedAt: ").Append(CheckedAt).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="KycResult" />
    /// </summary>
    public class KycResultJsonConverter : JsonConverter<KycResult>
    {
        /// <summary>
        /// The format to use to serialize CheckedAt
        /// </summary>
        public static string CheckedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="KycResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override KycResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> investorId = default;
            Option<KycResult.StatusEnum?> status = default;
            Option<DateTime?> checkedAt = default;
            Option<string?> reason = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "investorId":
                            investorId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<KycResult.StatusEnum?>(KycResult.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "checkedAt":
                            checkedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "reason":
                            reason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!investorId.IsSet)
                throw new ArgumentException("Property is required for class KycResult.", nameof(investorId));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class KycResult.", nameof(status));

            if (investorId.IsSet && investorId.Value == null)
                throw new ArgumentNullException(nameof(investorId), "Property is not nullable for class KycResult.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class KycResult.");

            if (checkedAt.IsSet && checkedAt.Value == null)
                throw new ArgumentNullException(nameof(checkedAt), "Property is not nullable for class KycResult.");

            if (reason.IsSet && reason.Value == null)
                throw new ArgumentNullException(nameof(reason), "Property is not nullable for class KycResult.");

            return new KycResult(investorId.Value!.Value!, status.Value!.Value!, checkedAt, reason);
        }

        /// <summary>
        /// Serializes a <see cref="KycResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="kycResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, KycResult kycResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, kycResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="KycResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="kycResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, KycResult kycResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (kycResult.ReasonOption.IsSet && kycResult.Reason == null)
                throw new ArgumentNullException(nameof(kycResult.Reason), "Property is required for class KycResult.");

            writer.WriteString("investorId", kycResult.InvestorId);

            var statusRawValue = KycResult.StatusEnumToJsonValue(kycResult.Status);
            writer.WriteString("status", statusRawValue);
            if (kycResult.CheckedAtOption.IsSet)
                writer.WriteString("checkedAt", kycResult.CheckedAtOption.Value!.Value.ToString(CheckedAtFormat));

            if (kycResult.ReasonOption.IsSet)
                writer.WriteString("reason", kycResult.Reason);
        }
    }
}
