// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// OrderResponse
    /// </summary>
    public partial class OrderResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="investorId">investorId</param>
        /// <param name="issuanceId">issuanceId</param>
        /// <param name="amount">amount</param>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        [JsonConstructor]
        public OrderResponse(Option<Guid?> id = default, Option<Guid?> investorId = default, Option<Guid?> issuanceId = default, Option<decimal?> amount = default, Option<StatusEnum?> status = default, Option<DateTime?> createdAt = default, Option<DateTime?> updatedAt = default)
        {
            IdOption = id;
            InvestorIdOption = investorId;
            IssuanceIdOption = issuanceId;
            AmountOption = amount;
            StatusOption = status;
            CreatedAtOption = createdAt;
            UpdatedAtOption = updatedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Created for value: created
            /// </summary>
            Created = 1,

            /// <summary>
            /// Enum Reserved for value: reserved
            /// </summary>
            Reserved = 2,

            /// <summary>
            /// Enum Paid for value: paid
            /// </summary>
            Paid = 3,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 4,

            /// <summary>
            /// Enum Cancelled for value: cancelled
            /// </summary>
            Cancelled = 5
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("created"))
                return StatusEnum.Created;

            if (value.Equals("reserved"))
                return StatusEnum.Reserved;

            if (value.Equals("paid"))
                return StatusEnum.Paid;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            if (value.Equals("cancelled"))
                return StatusEnum.Cancelled;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("created"))
                return StatusEnum.Created;

            if (value.Equals("reserved"))
                return StatusEnum.Reserved;

            if (value.Equals("paid"))
                return StatusEnum.Paid;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            if (value.Equals("cancelled"))
                return StatusEnum.Cancelled;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.Created)
                return "created";

            if (value == StatusEnum.Reserved)
                return "reserved";

            if (value == StatusEnum.Paid)
                return "paid";

            if (value == StatusEnum.Failed)
                return "failed";

            if (value == StatusEnum.Cancelled)
                return "cancelled";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InvestorId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> InvestorIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets InvestorId
        /// </summary>
        [JsonPropertyName("investorId")]
        public Guid? InvestorId { get { return this.InvestorIdOption; } set { this.InvestorIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IssuanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IssuanceIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets IssuanceId
        /// </summary>
        [JsonPropertyName("issuanceId")]
        public Guid? IssuanceId { get { return this.IssuanceIdOption; } set { this.IssuanceIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public decimal? Amount { get { return this.AmountOption; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTime? CreatedAt { get { return this.CreatedAtOption; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> UpdatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTime? UpdatedAt { get { return this.UpdatedAtOption; } set { this.UpdatedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  InvestorId: ").Append(InvestorId).Append("\n");
            sb.Append("  IssuanceId: ").Append(IssuanceId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrderResponse" />
    /// </summary>
    public class OrderResponseJsonConverter : JsonConverter<OrderResponse>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="OrderResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OrderResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> investorId = default;
            Option<Guid?> issuanceId = default;
            Option<decimal?> amount = default;
            Option<OrderResponse.StatusEnum?> status = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> updatedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "investorId":
                            investorId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "issuanceId":
                            issuanceId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "amount":
                            amount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<OrderResponse.StatusEnum?>(OrderResponse.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class OrderResponse.");

            if (investorId.IsSet && investorId.Value == null)
                throw new ArgumentNullException(nameof(investorId), "Property is not nullable for class OrderResponse.");

            if (issuanceId.IsSet && issuanceId.Value == null)
                throw new ArgumentNullException(nameof(issuanceId), "Property is not nullable for class OrderResponse.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class OrderResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class OrderResponse.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class OrderResponse.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class OrderResponse.");

            return new OrderResponse(id, investorId, issuanceId, amount, status, createdAt, updatedAt);
        }

        /// <summary>
        /// Serializes a <see cref="OrderResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OrderResponse orderResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, orderResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OrderResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OrderResponse orderResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (orderResponse.IdOption.IsSet)
                writer.WriteString("id", orderResponse.IdOption.Value!.Value);

            if (orderResponse.InvestorIdOption.IsSet)
                writer.WriteString("investorId", orderResponse.InvestorIdOption.Value!.Value);

            if (orderResponse.IssuanceIdOption.IsSet)
                writer.WriteString("issuanceId", orderResponse.IssuanceIdOption.Value!.Value);

            if (orderResponse.AmountOption.IsSet)
                writer.WriteNumber("amount", orderResponse.AmountOption.Value!.Value);

            var statusRawValue = OrderResponse.StatusEnumToJsonValue(orderResponse.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
            if (orderResponse.CreatedAtOption.IsSet)
                writer.WriteString("createdAt", orderResponse.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));

            if (orderResponse.UpdatedAtOption.IsSet)
                writer.WriteString("updatedAt", orderResponse.UpdatedAtOption.Value!.Value.ToString(UpdatedAtFormat));
        }
    }
}
