// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PayoutsReportResponse
    /// </summary>
    public partial class PayoutsReportResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayoutsReportResponse" /> class.
        /// </summary>
        /// <param name="period">period</param>
        /// <param name="items">items</param>
        /// <param name="totalAmount">totalAmount</param>
        [JsonConstructor]
        public PayoutsReportResponse(Option<PayoutsReportResponsePeriod?> period = default, Option<List<PayoutItem>?> items = default, Option<decimal?> totalAmount = default)
        {
            PeriodOption = period;
            ItemsOption = items;
            TotalAmountOption = totalAmount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Period
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PayoutsReportResponsePeriod?> PeriodOption { get; private set; }

        /// <summary>
        /// Gets or Sets Period
        /// </summary>
        [JsonPropertyName("period")]
        public PayoutsReportResponsePeriod? Period { get { return this.PeriodOption; } set { this.PeriodOption = new(value); } }

        /// <summary>
        /// Used to track the state of Items
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<PayoutItem>?> ItemsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [JsonPropertyName("items")]
        public List<PayoutItem>? Items { get { return this.ItemsOption; } set { this.ItemsOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> TotalAmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalAmount
        /// </summary>
        [JsonPropertyName("totalAmount")]
        public decimal? TotalAmount { get { return this.TotalAmountOption; } set { this.TotalAmountOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PayoutsReportResponse {\n");
            sb.Append("  Period: ").Append(Period).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  TotalAmount: ").Append(TotalAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PayoutsReportResponse" />
    /// </summary>
    public class PayoutsReportResponseJsonConverter : JsonConverter<PayoutsReportResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="PayoutsReportResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PayoutsReportResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PayoutsReportResponsePeriod?> period = default;
            Option<List<PayoutItem>?> items = default;
            Option<decimal?> totalAmount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "period":
                            period = new Option<PayoutsReportResponsePeriod?>(JsonSerializer.Deserialize<PayoutsReportResponsePeriod>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "items":
                            items = new Option<List<PayoutItem>?>(JsonSerializer.Deserialize<List<PayoutItem>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "totalAmount":
                            totalAmount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (period.IsSet && period.Value == null)
                throw new ArgumentNullException(nameof(period), "Property is not nullable for class PayoutsReportResponse.");

            if (items.IsSet && items.Value == null)
                throw new ArgumentNullException(nameof(items), "Property is not nullable for class PayoutsReportResponse.");

            if (totalAmount.IsSet && totalAmount.Value == null)
                throw new ArgumentNullException(nameof(totalAmount), "Property is not nullable for class PayoutsReportResponse.");

            return new PayoutsReportResponse(period, items, totalAmount);
        }

        /// <summary>
        /// Serializes a <see cref="PayoutsReportResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="payoutsReportResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PayoutsReportResponse payoutsReportResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, payoutsReportResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PayoutsReportResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="payoutsReportResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PayoutsReportResponse payoutsReportResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (payoutsReportResponse.PeriodOption.IsSet && payoutsReportResponse.Period == null)
                throw new ArgumentNullException(nameof(payoutsReportResponse.Period), "Property is required for class PayoutsReportResponse.");

            if (payoutsReportResponse.ItemsOption.IsSet && payoutsReportResponse.Items == null)
                throw new ArgumentNullException(nameof(payoutsReportResponse.Items), "Property is required for class PayoutsReportResponse.");

            if (payoutsReportResponse.PeriodOption.IsSet)
            {
                writer.WritePropertyName("period");
                JsonSerializer.Serialize(writer, payoutsReportResponse.Period, jsonSerializerOptions);
            }
            if (payoutsReportResponse.ItemsOption.IsSet)
            {
                writer.WritePropertyName("items");
                JsonSerializer.Serialize(writer, payoutsReportResponse.Items, jsonSerializerOptions);
            }
            if (payoutsReportResponse.TotalAmountOption.IsSet)
                writer.WriteNumber("totalAmount", payoutsReportResponse.TotalAmountOption.Value!.Value);
        }
    }
}
