// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// QualificationEvaluateRequest
    /// </summary>
    public partial class QualificationEvaluateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QualificationEvaluateRequest" /> class.
        /// </summary>
        /// <param name="investorId">investorId</param>
        /// <param name="amount">amount</param>
        [JsonConstructor]
        public QualificationEvaluateRequest(Guid investorId, decimal amount)
        {
            InvestorId = investorId;
            Amount = amount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets InvestorId
        /// </summary>
        [JsonPropertyName("investorId")]
        public Guid InvestorId { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public decimal Amount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QualificationEvaluateRequest {\n");
            sb.Append("  InvestorId: ").Append(InvestorId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Amount (decimal) minimum
            if (this.Amount < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for Amount, must be a value greater than or equal to 0.", new [] { "Amount" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="QualificationEvaluateRequest" />
    /// </summary>
    public class QualificationEvaluateRequestJsonConverter : JsonConverter<QualificationEvaluateRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="QualificationEvaluateRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override QualificationEvaluateRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> investorId = default;
            Option<decimal?> amount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "investorId":
                            investorId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "amount":
                            amount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!investorId.IsSet)
                throw new ArgumentException("Property is required for class QualificationEvaluateRequest.", nameof(investorId));

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class QualificationEvaluateRequest.", nameof(amount));

            if (investorId.IsSet && investorId.Value == null)
                throw new ArgumentNullException(nameof(investorId), "Property is not nullable for class QualificationEvaluateRequest.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class QualificationEvaluateRequest.");

            return new QualificationEvaluateRequest(investorId.Value!.Value!, amount.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="QualificationEvaluateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="qualificationEvaluateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, QualificationEvaluateRequest qualificationEvaluateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, qualificationEvaluateRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="QualificationEvaluateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="qualificationEvaluateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, QualificationEvaluateRequest qualificationEvaluateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("investorId", qualificationEvaluateRequest.InvestorId);

            writer.WriteNumber("amount", qualificationEvaluateRequest.Amount);
        }
    }
}
