// <auto-generated>
/*
 * OIS Gateway API
 *
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TxHistoryItem
    /// </summary>
    public partial class TxHistoryItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TxHistoryItem" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="type">type</param>
        /// <param name="issuanceId">issuanceId</param>
        /// <param name="issuanceCode">issuanceCode</param>
        /// <param name="amount">amount</param>
        /// <param name="status">status</param>
        /// <param name="dltTxHash">dltTxHash</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="confirmedAt">confirmedAt</param>
        [JsonConstructor]
        public TxHistoryItem(Option<Guid?> id = default, Option<TypeEnum?> type = default, Option<Guid?> issuanceId = default, Option<string?> issuanceCode = default, Option<decimal?> amount = default, Option<StatusEnum?> status = default, Option<string?> dltTxHash = default, Option<DateTime?> createdAt = default, Option<DateTime?> confirmedAt = default)
        {
            IdOption = id;
            TypeOption = type;
            IssuanceIdOption = issuanceId;
            IssuanceCodeOption = issuanceCode;
            AmountOption = amount;
            StatusOption = status;
            DltTxHashOption = dltTxHash;
            CreatedAtOption = createdAt;
            ConfirmedAtOption = confirmedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Transfer for value: transfer
            /// </summary>
            Transfer = 1,

            /// <summary>
            /// Enum Redeem for value: redeem
            /// </summary>
            Redeem = 2,

            /// <summary>
            /// Enum Issue for value: issue
            /// </summary>
            Issue = 3
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("transfer"))
                return TypeEnum.Transfer;

            if (value.Equals("redeem"))
                return TypeEnum.Redeem;

            if (value.Equals("issue"))
                return TypeEnum.Issue;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("transfer"))
                return TypeEnum.Transfer;

            if (value.Equals("redeem"))
                return TypeEnum.Redeem;

            if (value.Equals("issue"))
                return TypeEnum.Issue;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum? value)
        {
            if (value == TypeEnum.Transfer)
                return "transfer";

            if (value == TypeEnum.Redeem)
                return "redeem";

            if (value == TypeEnum.Issue)
                return "issue";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TypeEnum?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            Pending = 1,

            /// <summary>
            /// Enum Confirmed for value: confirmed
            /// </summary>
            Confirmed = 2,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("confirmed"))
                return StatusEnum.Confirmed;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("confirmed"))
                return StatusEnum.Confirmed;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.Pending)
                return "pending";

            if (value == StatusEnum.Confirmed)
                return "confirmed";

            if (value == StatusEnum.Failed)
                return "failed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IssuanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IssuanceIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets IssuanceId
        /// </summary>
        [JsonPropertyName("issuanceId")]
        public Guid? IssuanceId { get { return this.IssuanceIdOption; } set { this.IssuanceIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IssuanceCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IssuanceCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets IssuanceCode
        /// </summary>
        [JsonPropertyName("issuanceCode")]
        public string? IssuanceCode { get { return this.IssuanceCodeOption; } set { this.IssuanceCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public decimal? Amount { get { return this.AmountOption; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of DltTxHash
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DltTxHashOption { get; private set; }

        /// <summary>
        /// Gets or Sets DltTxHash
        /// </summary>
        [JsonPropertyName("dltTxHash")]
        public string? DltTxHash { get { return this.DltTxHashOption; } set { this.DltTxHashOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTime? CreatedAt { get { return this.CreatedAtOption; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of ConfirmedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ConfirmedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConfirmedAt
        /// </summary>
        [JsonPropertyName("confirmedAt")]
        public DateTime? ConfirmedAt { get { return this.ConfirmedAtOption; } set { this.ConfirmedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TxHistoryItem {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  IssuanceId: ").Append(IssuanceId).Append("\n");
            sb.Append("  IssuanceCode: ").Append(IssuanceCode).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  DltTxHash: ").Append(DltTxHash).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  ConfirmedAt: ").Append(ConfirmedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TxHistoryItem" />
    /// </summary>
    public class TxHistoryItemJsonConverter : JsonConverter<TxHistoryItem>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ConfirmedAt
        /// </summary>
        public static string ConfirmedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="TxHistoryItem" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TxHistoryItem Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<TxHistoryItem.TypeEnum?> type = default;
            Option<Guid?> issuanceId = default;
            Option<string?> issuanceCode = default;
            Option<decimal?> amount = default;
            Option<TxHistoryItem.StatusEnum?> status = default;
            Option<string?> dltTxHash = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> confirmedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<TxHistoryItem.TypeEnum?>(TxHistoryItem.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "issuanceId":
                            issuanceId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "issuanceCode":
                            issuanceCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "amount":
                            amount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<TxHistoryItem.StatusEnum?>(TxHistoryItem.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "dltTxHash":
                            dltTxHash = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "confirmedAt":
                            confirmedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class TxHistoryItem.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class TxHistoryItem.");

            if (issuanceId.IsSet && issuanceId.Value == null)
                throw new ArgumentNullException(nameof(issuanceId), "Property is not nullable for class TxHistoryItem.");

            if (issuanceCode.IsSet && issuanceCode.Value == null)
                throw new ArgumentNullException(nameof(issuanceCode), "Property is not nullable for class TxHistoryItem.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class TxHistoryItem.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class TxHistoryItem.");

            if (dltTxHash.IsSet && dltTxHash.Value == null)
                throw new ArgumentNullException(nameof(dltTxHash), "Property is not nullable for class TxHistoryItem.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class TxHistoryItem.");

            if (confirmedAt.IsSet && confirmedAt.Value == null)
                throw new ArgumentNullException(nameof(confirmedAt), "Property is not nullable for class TxHistoryItem.");

            return new TxHistoryItem(id, type, issuanceId, issuanceCode, amount, status, dltTxHash, createdAt, confirmedAt);
        }

        /// <summary>
        /// Serializes a <see cref="TxHistoryItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="txHistoryItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TxHistoryItem txHistoryItem, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, txHistoryItem, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TxHistoryItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="txHistoryItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TxHistoryItem txHistoryItem, JsonSerializerOptions jsonSerializerOptions)
        {
            if (txHistoryItem.IssuanceCodeOption.IsSet && txHistoryItem.IssuanceCode == null)
                throw new ArgumentNullException(nameof(txHistoryItem.IssuanceCode), "Property is required for class TxHistoryItem.");

            if (txHistoryItem.DltTxHashOption.IsSet && txHistoryItem.DltTxHash == null)
                throw new ArgumentNullException(nameof(txHistoryItem.DltTxHash), "Property is required for class TxHistoryItem.");

            if (txHistoryItem.IdOption.IsSet)
                writer.WriteString("id", txHistoryItem.IdOption.Value!.Value);

            var typeRawValue = TxHistoryItem.TypeEnumToJsonValue(txHistoryItem.TypeOption.Value!.Value);
            writer.WriteString("type", typeRawValue);
            if (txHistoryItem.IssuanceIdOption.IsSet)
                writer.WriteString("issuanceId", txHistoryItem.IssuanceIdOption.Value!.Value);

            if (txHistoryItem.IssuanceCodeOption.IsSet)
                writer.WriteString("issuanceCode", txHistoryItem.IssuanceCode);

            if (txHistoryItem.AmountOption.IsSet)
                writer.WriteNumber("amount", txHistoryItem.AmountOption.Value!.Value);

            var statusRawValue = TxHistoryItem.StatusEnumToJsonValue(txHistoryItem.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
            if (txHistoryItem.DltTxHashOption.IsSet)
                writer.WriteString("dltTxHash", txHistoryItem.DltTxHash);

            if (txHistoryItem.CreatedAtOption.IsSet)
                writer.WriteString("createdAt", txHistoryItem.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));

            if (txHistoryItem.ConfirmedAtOption.IsSet)
                writer.WriteString("confirmedAt", txHistoryItem.ConfirmedAtOption.Value!.Value.ToString(ConfirmedAtFormat));
        }
    }
}
