apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.x
    helm:
      values: |
        configs:
          params:
            server.insecure: false
          cm:
            url: https://argocd.ois-cfa.example.com
          rbac:
            policy.default: role:readonly
            policy.csv: |
              p, role:org-admin, applications, *, */*, allow
              p, role:org-admin, clusters, get, *, allow
              p, role:org-admin, repositories, get, *, allow
              p, role:org-admin, repositories, create, *, allow
              p, role:org-admin, repositories, update, *, allow
              p, role:org-admin, repositories, delete, *, allow
              p, role:developer, applications, get, */*, allow
              p, role:developer, applications, sync, */*, allow
              p, role:developer, applications, override, */*, allow
              p, role:auditor, applications, get, */*, allow
              p, role:auditor, logs, get, */*, allow
        oidc:
          name: Keycloak
          issuer: https://keycloak.ois-cfa.example.com/realms/argocd
          clientId: argocd
          requestedScopes: ["openid", "profile", "email", "groups"]
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

