@startuml
' Generated 2025-10-31 13:21  (Asia/Tokyo)
start
:Получить обращение;
:Классификация и SLA;
if (ИБ-инцидент?) then (да)
  :Эскалация в Security/SOC;
else (нет)
  :Назначить владельца;
endif
:Ответ пользователю и закрытие;
stop

@enduml
