/* tslint:disable */
/* eslint-disable */
/**
 * OIS Gateway API
 * API Gateway для оператора информационной системы ЦФА
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PayoutHistoryResponse,
  ProblemDetails,
  TransactionHistoryResponse,
} from '../models/index';
import {
    PayoutHistoryResponseFromJSON,
    PayoutHistoryResponseToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    TransactionHistoryResponseFromJSON,
    TransactionHistoryResponseToJSON,
} from '../models/index';

export interface GetInvestorPayoutsRequest {
    id: string;
    from?: Date;
    to?: Date;
}

export interface GetInvestorTransactionsRequest {
    id: string;
    from?: Date;
    to?: Date;
    type?: GetInvestorTransactionsTypeEnum;
}

/**
 * 
 */
export class InvestorsApi extends runtime.BaseAPI {

    /**
     * Get investor payout history
     */
    async getInvestorPayoutsRaw(requestParameters: GetInvestorPayoutsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PayoutHistoryResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getInvestorPayouts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/investors/{id}/payouts`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PayoutHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Get investor payout history
     */
    async getInvestorPayouts(requestParameters: GetInvestorPayoutsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PayoutHistoryResponse> {
        const response = await this.getInvestorPayoutsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get investor transaction history
     */
    async getInvestorTransactionsRaw(requestParameters: GetInvestorTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionHistoryResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getInvestorTransactions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/investors/{id}/transactions`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Get investor transaction history
     */
    async getInvestorTransactions(requestParameters: GetInvestorTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionHistoryResponse> {
        const response = await this.getInvestorTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetInvestorTransactionsTypeEnum = {
    Transfer: 'transfer',
    Redeem: 'redeem',
    Issue: 'issue',
    All: 'all'
} as const;
export type GetInvestorTransactionsTypeEnum = typeof GetInvestorTransactionsTypeEnum[keyof typeof GetInvestorTransactionsTypeEnum];
